let mode = "encode"; let source = "text"; let selectedFile = null; let outputBytes = null; let outputMime = "application/octet-stream";
const input = document.querySelector("#input-text"); const output = document.querySelector("#output-text"); const status = document.querySelector("#status");
const bytesToBase64 = bytes => { let binary = ""; const chunk = 0x8000; for (let i = 0; i < bytes.length; i += chunk) binary += String.fromCharCode(...bytes.subarray(i, i + chunk)); return btoa(binary); };
const base64ToBytes = text => { const clean = text.replace(/\s/g, ""); if (!clean || !/^[A-Za-z0-9+/]*={0,2}$/.test(clean) || clean.length % 4 === 1) throw new Error("Input is not valid Base64."); const binary = atob(clean); return Uint8Array.from(binary, char => char.charCodeAt(0)); };
const utf8 = new TextEncoder(); const decoder = new TextDecoder(); const byteLabel = count => `${count.toLocaleString()} byte${count === 1 ? "" : "s"}`;
function convert() { try { let bytes; if (mode === "encode") { if (source === "file") { if (!selectedFile) throw new Error("Choose a file to encode."); outputMime = selectedFile.type || "application/octet-stream"; } else { bytes = utf8.encode(input.value); outputMime = "text/plain;charset=utf-8"; } } else { bytes = base64ToBytes(input.value); outputMime = "application/octet-stream"; } if (source === "file" && mode === "encode") { selectedFile.arrayBuffer().then(buffer => finish(new Uint8Array(buffer))).catch(error => fail(error)); } else finish(bytes); } catch (error) { fail(error); } }
function finish(bytes) { if (mode === "encode") { output.value = bytesToBase64(bytes); outputBytes = bytes; status.textContent = `${source === "file" ? "File" : "Text"} encoded to Base64.`; } else { output.value = decoder.decode(bytes); outputBytes = bytes; status.textContent = "Base64 decoded as UTF-8 text. Download bytes for binary data."; } document.querySelector("#input-size").textContent = `Input: ${byteLabel(bytes.length)}`; document.querySelector("#output-size").textContent = `Output: ${byteLabel(output.value.length)}`; status.className = "status"; }
function fail(error) { output.value = ""; outputBytes = null; status.className = "status error"; status.textContent = error.message; document.querySelector("#input-size").textContent = "Input: 0 bytes"; document.querySelector("#output-size").textContent = "Output: 0 bytes"; }
function updateUi() { const encoding = mode === "encode"; document.querySelector("#convert-button").textContent = encoding ? `Encode ${source === "file" ? "file" : "text"}` : "Decode Base64"; document.querySelector("#input-label-text").textContent = encoding ? "Text input" : "Base64 input"; if (encoding && source === "file") { document.querySelector("#input-label").hidden = true; document.querySelector("#file-label").hidden = false; } else { document.querySelector("#input-label").hidden = false; document.querySelector("#file-label").hidden = true; } status.textContent = encoding ? "Ready to encode." : "Ready to decode."; status.className = "status"; }
document.querySelectorAll("[data-mode]").forEach(button => button.addEventListener("click", () => { mode = button.dataset.mode; document.querySelectorAll("[data-mode]").forEach(item => { item.classList.toggle("active", item === button); item.setAttribute("aria-pressed", item === button); }); updateUi(); })); document.querySelector("#source-mode").addEventListener("change", event => { source = event.target.value; selectedFile = null; updateUi(); }); document.querySelector("#file-input").addEventListener("change", event => { selectedFile = event.target.files[0] || null; if (selectedFile) { input.value = selectedFile.name; status.textContent = `${selectedFile.name} ready to encode.`; } }); document.querySelector("#convert-button").addEventListener("click", convert);
document.querySelector("#copy-button").addEventListener("click", async () => { if (!output.value) return; try { await navigator.clipboard.writeText(output.value); status.textContent = "Output copied to the clipboard."; } catch { status.className = "status error"; status.textContent = "Copy was unavailable; select the output manually."; } }); document.querySelector("#download-button").addEventListener("click", () => { if (!outputBytes) { status.className = "status error"; status.textContent = "Convert something before downloading bytes."; return; } const bytes = mode === "encode" ? new Blob([output.value], { type: "text/plain;charset=utf-8" }) : new Blob([outputBytes], { type: outputMime }); const link = document.createElement("a"); link.href = URL.createObjectURL(bytes); link.download = mode === "encode" ? "encoded-base64.txt" : "decoded-output.bin"; link.click(); URL.revokeObjectURL(link.href); status.textContent = "Download prepared."; }); document.querySelector("#clear-button").addEventListener("click", () => { input.value = ""; output.value = ""; selectedFile = null; outputBytes = null; status.textContent = "Ready to encode."; status.className = "status"; }); updateUi(); convert();
