let context; let master; let nodes = {}; let playing = false;
const AudioContextClass = window.AudioContext || window.webkitAudioContext;
const channelTypes = { rain: { type: "noise", frequency: 2600 }, noise: { type: "noise", frequency: 8000 }, fan: { type: "noise", frequency: 120 }, tone: { type: "tone", frequency: 220 } };
function noiseBuffer() { const buffer = context.createBuffer(1, context.sampleRate * 2, context.sampleRate); const data = buffer.getChannelData(0); for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1; return buffer; }
function createAudio() { context = new AudioContextClass(); master = context.createGain(); master.gain.value = Number(document.querySelector("#master-volume").value); master.connect(context.destination); Object.keys(channelTypes).forEach(name => { const config = channelTypes[name]; const gain = context.createGain(); gain.gain.value = 0; gain.connect(master); if (config.type === "tone") { const oscillator = context.createOscillator(); oscillator.frequency.value = config.frequency; oscillator.type = "sine"; oscillator.connect(gain); oscillator.start(); nodes[name] = { gain, oscillator }; } else { const source = context.createBufferSource(); const filter = context.createBiquadFilter(); source.buffer = noiseBuffer(); source.loop = true; filter.type = name === "fan" ? "lowpass" : name === "rain" ? "highpass" : "bandpass"; filter.frequency.value = config.frequency; filter.Q.value = name === "rain" ? .4 : .8; source.connect(filter); filter.connect(gain); source.start(); nodes[name] = { gain, source }; } }); }
function setGain(name, value) { if (nodes[name]) nodes[name].gain.gain.setTargetAtTime(value, context.currentTime, .03); }
async function start() { if (!AudioContextClass) { document.querySelector("#status").textContent = "Web Audio is not supported in this browser."; return; } if (!context) createAudio(); await context.resume(); playing = true; document.querySelectorAll(".channel").forEach(channel => { const name = channel.dataset.channel; const on = channel.querySelector(".channel-toggle").checked; setGain(name, on ? Number(channel.querySelector(".volume").value) : 0); }); document.querySelector("#play-button").textContent = "Soundscape playing"; document.querySelector("#status").textContent = "Soundscape is playing locally."; }
function stop() { if (context) { Object.keys(nodes).forEach(name => setGain(name, 0)); context.suspend(); } playing = false; document.querySelector("#play-button").textContent = "Start soundscape"; document.querySelector("#status").textContent = "Soundscape paused."; }
document.querySelector("#play-button").addEventListener("click", start); document.querySelector("#stop-button").addEventListener("click", stop); document.querySelector("#master-volume").addEventListener("input", event => { document.querySelector("#master-output").textContent = `${Math.round(event.target.value * 100)}%`; if (master) master.gain.setTargetAtTime(event.target.value, context.currentTime, .03); }); document.querySelectorAll(".channel").forEach(channel => { const name = channel.dataset.channel; const toggle = channel.querySelector(".channel-toggle"); const volume = channel.querySelector(".volume"); toggle.addEventListener("change", () => { if (playing) setGain(name, toggle.checked ? Number(volume.value) : 0); }); volume.addEventListener("input", () => { channel.querySelector("output").textContent = `${Math.round(volume.value * 100)}%`; if (playing && toggle.checked) setGain(name, Number(volume.value)); }); }); document.querySelectorAll("[data-preset]").forEach(button => button.addEventListener("click", () => { const preset = { rain: { rain: .7, noise: 0, fan: 0, tone: 0 }, focus: { rain: .2, noise: .25, fan: .3, tone: .1 }, quiet: { rain: 0, noise: 0, fan: .2, tone: .1 } }[button.dataset.preset]; document.querySelectorAll(".channel").forEach(channel => { const value = preset[channel.dataset.channel]; channel.querySelector(".volume").value = value; channel.querySelector(".channel-toggle").checked = value > 0; channel.querySelector("output").textContent = `${Math.round(value * 100)}%`; }); if (playing) start(); document.querySelector("#status").textContent = `${button.textContent} preset loaded.`; }));
