const canvas = document.querySelector("#game"); const ctx = canvas.getContext("2d"); const holdCanvas = document.querySelector("#hold"); const holdCtx = holdCanvas.getContext("2d"); const nextCanvas = document.querySelector("#next"); const nextCtx = nextCanvas.getContext("2d"); const status = document.querySelector("#status"); const colors = ["#000", "#74d8e8", "#6e86ef", "#e99af0", "#f4d264", "#90dd78", "#f0a164", "#a992f0"]; const shapes = [[[1,1,1,1]], [[1,0,0],[1,1,1]], [[0,0,1],[1,1,1]], [[1,1],[1,1]], [[0,1,1],[1,1,0]], [[0,1,0],[1,1,1]], [[1,1,0],[0,1,1]]]; let board; let current; let next; let held; let canHold; let score; let level; let lines; let running = false; let paused = false; let animation; let lastDrop = 0;
function randomPiece() { const type = Math.floor(Math.random() * shapes.length); const shape = shapes[type].map(row => [...row]); return { shape, x: Math.floor((10 - shape[0].length) / 2), y: 0, color: type + 1 }; }
function clonePiece(piece) { return { ...piece, shape: piece.shape.map(row => [...row]) }; }
function collide(piece, dx = 0, dy = 0, shape = piece.shape) { return shape.some((row, y) => row.some((cell, x) => cell && (piece.x + x + dx < 0 || piece.x + x + dx >= 10 || piece.y + y + dy >= 20 || (piece.y + y + dy >= 0 && board[piece.y + y + dy][piece.x + x + dx])))); }
function rotate() { const shape = current.shape[0].map((_, x) => current.shape.map(row => row[x]).reverse()); if (!collide(current, 0, 0, shape)) current.shape = shape; else if (!collide(current, -1, 0, shape)) { current.x--; current.shape = shape; } else if (!collide(current, 1, 0, shape)) { current.x++; current.shape = shape; } }
function merge() { current.shape.forEach((row, y) => row.forEach((cell, x) => { if (cell && current.y + y >= 0) board[current.y + y][current.x + x] = current.color; })); const full = board.filter(row => row.every(Boolean)).length; if (full) { board = board.filter(row => !row.every(Boolean)); while (board.length < 20) board.unshift(Array(10).fill(0)); lines += full; score += [0, 100, 300, 500, 800][full] * level; level = Math.floor(lines / 10) + 1; } current = next; next = randomPiece(); canHold = true; if (collide(current)) endGame(); updateHud(); }
function drop() { if (!collide(current, 0, 1)) current.y++; else merge(); }
function ghost() { const piece = clonePiece(current); while (!collide(piece, 0, 1)) piece.y++; return piece; }
function drawPiece(context, piece, size, ghostPiece = false) { piece.shape.forEach((row, y) => row.forEach((cell, x) => { if (!cell) return; context.fillStyle = ghostPiece ? `${colors[piece.color]}55` : colors[piece.color]; context.fillRect((piece.x + x) * size, (piece.y + y) * size, size - 1, size - 1); })); }
function draw() { ctx.fillStyle = "#0b130d"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "#142219"; for (let x = 0; x <= 10; x++) { ctx.beginPath(); ctx.moveTo(x * 30, 0); ctx.lineTo(x * 30, 600); ctx.stroke(); } for (let y = 0; y <= 20; y++) { ctx.beginPath(); ctx.moveTo(0, y * 30); ctx.lineTo(300, y * 30); ctx.stroke(); } board.forEach((row, y) => row.forEach((value, x) => { if (value) { ctx.fillStyle = colors[value]; ctx.fillRect(x * 30, y * 30, 29, 29); } })); if (current) { const ghostPiece = ghost(); drawPiece(ctx, ghostPiece, 30, true); drawPiece(ctx, current, 30); } drawPreview(holdCtx, held); drawPreview(nextCtx, next); }
function drawPreview(context, piece) { context.fillStyle = "#0f150f"; context.fillRect(0, 0, 120, 90); if (!piece) return; const size = 22; const offsetX = (120 - piece.shape[0].length * size) / 2; const offsetY = (90 - piece.shape.length * size) / 2; context.save(); context.translate(offsetX, offsetY); drawPiece(context, { ...piece, x: 0, y: 0 }, size); context.restore(); }
function updateHud() { document.querySelector("#score").textContent = score; document.querySelector("#level").textContent = level; document.querySelector("#lines").textContent = lines; }
function frame(time) { if (!running || paused) return; if (time - lastDrop > Math.max(90, 700 - (level - 1) * 55)) { drop(); lastDrop = time; } draw(); animation = requestAnimationFrame(frame); }
function start() { if (running && !paused) return; if (!running) { board = Array.from({ length: 20 }, () => Array(10).fill(0)); current = randomPiece(); next = randomPiece(); held = null; canHold = true; score = 0; lines = 0; level = 1; running = true; } paused = false; status.textContent = "Place pieces and clear lines."; status.className = "status good"; animation = requestAnimationFrame(frame); }
function hold() { if (!canHold) return; canHold = false; if (!held) { held = current; current = next; next = randomPiece(); } else { [held, current] = [current, held]; current.x = Math.floor((10 - current.shape[0].length) / 2); current.y = 0; } if (collide(current)) endGame(); draw(); }
function endGame() { running = false; paused = false; cancelAnimationFrame(animation); status.textContent = `Game over — score ${score}.`; status.className = "status error"; draw(); }
function action(name) { if (!running) start(); if (name === "left" && !collide(current, -1, 0)) current.x--; if (name === "right" && !collide(current, 1, 0)) current.x++; if (name === "down") drop(); if (name === "rotate") rotate(); if (name === "drop") while (!collide(current, 0, 1)) current.y++; if (name === "hold") hold(); draw(); }
document.addEventListener("keydown", event => { const actions = { ArrowLeft: "left", ArrowRight: "right", ArrowDown: "down", ArrowUp: "rotate", " ": "drop", c: "hold" }; if (actions[event.key]) { event.preventDefault(); action(actions[event.key]); } }); document.querySelectorAll("[data-action]").forEach(button => button.addEventListener("click", () => action(button.dataset.action))); document.querySelector("#start-button").addEventListener("click", () => { running = false; cancelAnimationFrame(animation); start(); }); document.querySelector("#pause-button").addEventListener("click", () => { if (!running) return; paused = !paused; status.textContent = paused ? "Paused." : "Place pieces and clear lines."; status.className = "status"; if (!paused) animation = requestAnimationFrame(frame); }); board = Array.from({ length: 20 }, () => Array(10).fill(0)); current = randomPiece(); next = randomPiece(); held = null; canHold = true; score = 0; level = 1; lines = 0; updateHud(); draw();
