const canvas = document.querySelector("#game"); const ctx = canvas.getContext("2d"); const status = document.querySelector("#status"); const scoreOutput = document.querySelector("#score"); const levelOutput = document.querySelector("#level"); const livesOutput = document.querySelector("#lives"); let paddle; let ball; let bricks; let score; let level; let lives; let running = false; let paused = false; let animation; let move = 0; const bestKey = "breakout-best"; let best = 0; try { best = Number(localStorage.getItem(bestKey)) || 0; } catch {}
function resetBall() { ball = { x: canvas.width / 2, y: canvas.height - 48, dx: 2.7 + level * .25, dy: -(3.2 + level * .2), radius: 7 }; paddle = { x: canvas.width / 2 - 42, y: canvas.height - 20, width: 84, height: 10, speed: 6 }; }
function buildBricks() { const rows = Math.min(5 + level, 8); const cols = 8; bricks = []; for (let row = 0; row < rows; row++) for (let col = 0; col < cols; col++) bricks.push({ x: 25 + col * 54, y: 28 + row * 20, width: 47, height: 13, alive: true, color: row % 2 ? "#8fcf68" : "#ffab73" }); }
function draw() { ctx.fillStyle = "#0e1811"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "#162619"; for (let x = 0; x < canvas.width; x += 24) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } bricks.forEach(brick => { if (brick.alive) { ctx.fillStyle = brick.color; ctx.fillRect(brick.x, brick.y, brick.width, brick.height); } }); ctx.fillStyle = "#c7f487"; ctx.fillRect(paddle.x, paddle.y, paddle.width, paddle.height); ctx.fillStyle = "#fff0b0"; ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2); ctx.fill(); }
function updateHud() { scoreOutput.textContent = score; levelOutput.textContent = level; livesOutput.textContent = lives; }
function movePaddle(amount) { paddle.x = Math.max(0, Math.min(canvas.width - paddle.width, paddle.x + amount)); }
function collision() { if (ball.x + ball.radius > canvas.width || ball.x - ball.radius < 0) ball.dx *= -1; if (ball.y - ball.radius < 0) ball.dy = Math.abs(ball.dy); if (ball.dy > 0 && ball.y + ball.radius >= paddle.y && ball.y - ball.radius <= paddle.y + paddle.height && ball.x >= paddle.x && ball.x <= paddle.x + paddle.width) { const offset = (ball.x - (paddle.x + paddle.width / 2)) / (paddle.width / 2); ball.dx = offset * 5; ball.dy = -Math.abs(ball.dy); } bricks.forEach(brick => { if (!brick.alive || ball.x + ball.radius < brick.x || ball.x - ball.radius > brick.x + brick.width || ball.y + ball.radius < brick.y || ball.y - ball.radius > brick.y + brick.height) return; brick.alive = false; score += 10; ball.dy *= -1; }); }
function frame() { if (!running || paused) return; movePaddle(move); move = 0; ball.x += ball.dx; ball.y += ball.dy; collision(); if (ball.y - ball.radius > canvas.height) { lives--; updateHud(); if (!lives) return endGame(); resetBall(); } if (!bricks.some(brick => brick.alive)) { level++; score += 50; buildBricks(); resetBall(); status.textContent = `Level ${level} — keep the rhythm.`; status.className = "status good"; } if (score > best) { best = score; try { localStorage.setItem(bestKey, String(best)); } catch {} } draw(); animation = requestAnimationFrame(frame); }
function start() { if (running && !paused) return; if (!running) { score = 0; level = 1; lives = 3; buildBricks(); resetBall(); running = true; } paused = false; status.textContent = "Keep the ball in play."; status.className = "status good"; updateHud(); cancelAnimationFrame(animation); animation = requestAnimationFrame(frame); }
function endGame() { running = false; paused = false; cancelAnimationFrame(animation); status.textContent = `Game over — score ${score}.`; status.className = "status error"; draw(); }
function restart() { running = false; cancelAnimationFrame(animation); start(); }
document.addEventListener("keydown", event => { if (["ArrowLeft", "ArrowRight", "a", "d", " "].includes(event.key)) event.preventDefault(); if (event.key === "ArrowLeft" || event.key === "a") move = -paddle.speed; if (event.key === "ArrowRight" || event.key === "d") move = paddle.speed; if (event.key === " ") start(); }); document.querySelector("#start-button").addEventListener("click", start); document.querySelector("#pause-button").addEventListener("click", () => { if (!running) return; paused = !paused; status.textContent = paused ? "Paused." : "Keep the ball in play."; status.className = "status"; if (!paused) animation = requestAnimationFrame(frame); }); document.querySelector("#left-button").addEventListener("pointerdown", () => { move = -paddle.speed; }); document.querySelector("#right-button").addEventListener("pointerdown", () => { move = paddle.speed; }); canvas.addEventListener("pointermove", event => { const rect = canvas.getBoundingClientRect(); paddle.x = (event.clientX - rect.left) / rect.width * canvas.width - paddle.width / 2; paddle.x = Math.max(0, Math.min(canvas.width - paddle.width, paddle.x)); draw(); }); resetBall(); score = 0; level = 1; lives = 3; buildBricks(); updateHud(); draw();
