const race = document.querySelector("#race"); const size = document.querySelector("#size"); const speed = document.querySelector("#speed"); const status = document.querySelector("#status"); const algorithms = [{ name: "Bubble sort", note: "Repeatedly settles the largest value.", key: "bubble" }, { name: "Selection sort", note: "Finds the next smallest value.", key: "selection" }, { name: "Insertion sort", note: "Builds an ordered left side.", key: "insertion" }]; let source = []; let runners = []; let timer;
function* bubble(values) { let array = [...values]; let comparisons = 0; let swaps = 0; for (let end = array.length - 1; end > 0; end--) for (let index = 0; index < end; index++) { comparisons++; if (array[index] > array[index + 1]) { [array[index], array[index + 1]] = [array[index + 1], array[index]]; swaps++; } yield { array: [...array], comparisons, swaps }; } return { array, comparisons, swaps }; }
function* selection(values) { let array = [...values]; let comparisons = 0; let swaps = 0; for (let start = 0; start < array.length - 1; start++) { let smallest = start; for (let index = start + 1; index < array.length; index++) { comparisons++; if (array[index] < array[smallest]) smallest = index; yield { array: [...array], comparisons, swaps }; } if (smallest !== start) { [array[start], array[smallest]] = [array[smallest], array[start]]; swaps++; } } return { array, comparisons, swaps }; }
function* insertion(values) { const array = [...values]; let comparisons = 0; let swaps = 0; for (let index = 1; index < array.length; index++) { let cursor = index; while (cursor > 0) { comparisons++; if (array[cursor - 1] <= array[cursor]) break; [array[cursor - 1], array[cursor]] = [array[cursor], array[cursor - 1]]; cursor--; swaps++; yield { array: [...array], comparisons, swaps }; } } return { array, comparisons, swaps }; }
function buildCards() { race.innerHTML = algorithms.map(item => `<article class="race-card" data-key="${item.key}"><h2>${item.name}</h2><p>${item.note}</p><div class="bar-chart" aria-label="${item.name} bars"></div><div class="metrics"><div>Comparisons<strong class="comparisons">0</strong></div><div>Swaps<strong class="swaps">0</strong></div><div class="state">Ready</div></div></article>`).join(""); }
function renderBars() { race.querySelectorAll(".race-card").forEach((card, index) => { const values = runners[index]?.current || source; card.querySelector(".bar-chart").innerHTML = values.map(value => `<span class="bar" style="height:${Math.max(3, value / 100 * 100)}%"></span>`).join(""); }); }
function newData() { source = Array.from({ length: Number(size.value) }, () => 10 + Math.floor(Math.random() * 90)); runners = []; buildCards(); renderBars(); status.textContent = "All algorithms receive the same shuffled values."; }
function start() { clearInterval(timer); runners = [bubble(source), selection(source), insertion(source)].map(generator => ({ generator, current: [...source], comparisons: 0, swaps: 0, done: false })); status.textContent = "The race is underway."; timer = setInterval(() => { let finished = 0; runners.forEach((runner, index) => { if (runner.done) { finished++; return; } const result = runner.generator.next(); if (result.done) { runner.done = true; finished++; } else { runner.current = result.value.array; runner.comparisons = result.value.comparisons; runner.swaps = result.value.swaps; } const card = race.querySelectorAll(".race-card")[index]; card.querySelector(".comparisons").textContent = runner.comparisons; card.querySelector(".swaps").textContent = runner.swaps; card.querySelector(".state").textContent = runner.done ? "Finished" : "Sorting…"; card.querySelector(".state").className = `state ${runner.done ? "done" : ""}`; }); renderBars(); if (finished === runners.length) { clearInterval(timer); status.textContent = "Race complete. Compare the strategies above."; } }, Number(speed.value) === 1 ? 90 : Number(speed.value) === 2 ? 35 : 10); }
document.querySelector("#start").addEventListener("click", start); document.querySelector("#reset").addEventListener("click", newData); size.addEventListener("input", () => { document.querySelector("#size-value").textContent = size.value; newData(); }); speed.addEventListener("input", () => { document.querySelector("#speed-value").textContent = ["Slow", "Medium", "Fast"][Number(speed.value) - 1]; }); document.querySelector("#size-value").textContent = size.value; document.querySelector("#speed-value").textContent = "Fast"; newData();
