const mazeElement = document.querySelector("#maze"); const status = document.querySelector("#status"); const badge = document.querySelector("#status-badge"); const sizeSelect = document.querySelector("#size"); const algorithm = document.querySelector("#algorithm"); let size; let grid; let path; let visited; let animating = false; let animation;
function index(row, col) { return row * size + col; } function neighbors(row, col) { return [[row - 1, col], [row + 1, col], [row, col - 1], [row, col + 1]].filter(([r, c]) => r >= 0 && r < size && c >= 0 && c < size); }
function generate() { grid = Array.from({ length: size }, () => Array(size).fill(false)); const seen = new Set(); const carve = (row, col) => { seen.add(index(row, col)); const directions = [[-2, 0], [2, 0], [0, -2], [0, 2]].sort(() => Math.random() - .5); directions.forEach(([dr, dc]) => { const nr = row + dr; const nc = col + dc; if (nr > 0 && nr < size - 1 && nc > 0 && nc < size - 1 && !seen.has(index(nr, nc))) { grid[row + dr / 2][col + dc / 2] = true; grid[nr][nc] = true; carve(nr, nc); } }); }; grid[1][1] = true; carve(1, 1); path = []; visited = []; }
function render(extra = {}) { mazeElement.style.gridTemplateColumns = `repeat(${size}, 1fr)`; mazeElement.innerHTML = grid.flatMap((row, r) => row.map((open, c) => { const cell = index(r, c); const classes = ["cell", open ? "open" : "", r === 1 && c === 1 ? "start" : "", r === size - 2 && c === size - 2 ? "end" : "", extra.visited?.has(cell) ? "visited" : "", extra.path?.has(cell) ? "path" : ""]; return `<div class="${classes.join(" ")}" role="gridcell" aria-label="${r === 1 && c === 1 ? "Start" : r === size - 2 && c === size - 2 ? "End" : open ? "Open path" : "Wall"}"></div>`; })).join(""); }
function solveSearch() { const start = index(1, 1); const end = index(size - 2, size - 2); const queue = [start]; const came = new Map([[start, null]]); const distance = new Map([[start, 0]]); while (queue.length) { const current = queue.shift(); if (current === end) break; const row = Math.floor(current / size); const col = current % size; const next = neighbors(row, col).filter(([r, c]) => grid[r][c]).map(([r, c]) => index(r, c)).filter(item => !came.has(item)); next.forEach(item => { came.set(item, current); distance.set(item, distance.get(current) + 1); queue.push(item); }); if (algorithm.value === "astar") queue.sort((a, b) => distance.get(a) + heuristic(a, end) - distance.get(b) - heuristic(b, end)); } if (!came.has(end)) return null; const route = []; let cursor = end; while (cursor !== null) { route.unshift(cursor); cursor = came.get(cursor); } return { route, order: [...came.keys()], distance: distance.get(end) }; }
function heuristic(a, b) { return Math.abs(Math.floor(a / size) - Math.floor(b / size)) + Math.abs(a % size - b % size); }
function animate(solution) { clearInterval(animation); animating = true; let step = 0; const explored = new Set(); const route = new Set(); animation = setInterval(() => { if (step < solution.order.length) explored.add(solution.order[step++]); else if (step < solution.order.length + solution.route.length) route.add(solution.route[step++ - solution.order.length]); else { clearInterval(animation); animating = false; status.textContent = `${algorithm.value === "astar" ? "A*" : "BFS"} found a ${solution.distance}-step route.`; status.className = "status good"; } render({ visited: explored, path: route }); }, 16); }
function newMaze() { clearInterval(animation); animating = false; size = Number(sizeSelect.value); generate(); render(); status.textContent = "Generate a maze to begin."; status.className = "status"; badge.textContent = `${algorithm.value === "astar" ? "A*" : "BFS"} ready`; }
document.querySelector("#new-maze").addEventListener("click", newMaze); sizeSelect.addEventListener("change", newMaze); algorithm.addEventListener("change", () => { badge.textContent = `${algorithm.value === "astar" ? "A*" : "BFS"} ready`; }); document.querySelector("#clear-path").addEventListener("click", () => { clearInterval(animation); animating = false; visited = []; path = []; render(); status.textContent = "Search path cleared."; status.className = "status"; }); document.querySelector("#solve").addEventListener("click", () => { if (animating) return; const solution = solveSearch(); if (solution) { status.textContent = `Searching with ${algorithm.value === "astar" ? "A*" : "BFS"}…`; status.className = "status"; animate(solution); } else { status.textContent = "No route found in this maze."; status.className = "status error"; } }); newMaze();
