const columns = [{ id: "backlog", title: "Backlog" }, { id: "doing", title: "In progress" }, { id: "done", title: "Done" }];
const sample = [{ id: 1, text: "Sketch the next small step", column: "backlog" }, { id: 2, text: "Build the useful middle", column: "doing" }, { id: 3, text: "Ship something clear", column: "done" }];
let tasks; let draggedId = null;
try { tasks = JSON.parse(localStorage.getItem("kanban-board-tasks")) || sample; } catch { tasks = sample; }
const board = document.querySelector("#board"); const status = document.querySelector("#status"); const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
function save(message = "Board saved locally.") { localStorage.setItem("kanban-board-tasks", JSON.stringify(tasks)); status.textContent = message; document.querySelector("#task-count").textContent = `${tasks.length} ${tasks.length === 1 ? "task" : "tasks"}`; }
function render() { board.innerHTML = columns.map(column => { const items = tasks.filter(task => task.column === column.id); return `<section class="column" data-column="${column.id}" aria-labelledby="heading-${column.id}"><div class="column-heading"><h3 id="heading-${column.id}">${column.title}</h3><span>${items.length}</span></div><div class="cards">${items.map((task, index) => `<article class="card" draggable="true" data-task="${task.id}" tabindex="0"><p>${escapeHtml(task.text)}</p><div class="card-meta"><small>Card ${index + 1}</small><div class="card-actions"><button type="button" data-move="-1" aria-label="Move ${escapeHtml(task.text)} left" ${column.id === "backlog" ? "disabled" : ""}>←</button><button type="button" data-move="1" aria-label="Move ${escapeHtml(task.text)} right" ${column.id === "done" ? "disabled" : ""}>→</button><button type="button" data-delete aria-label="Delete ${escapeHtml(task.text)}">×</button></div></div></article>`).join("") || "<p class=\"empty-column\">Drop a task here</p>"}</div></section>`; }).join(""); attachEvents(); save(); }
function move(id, direction) { const task = tasks.find(item => item.id === id); const index = columns.findIndex(column => column.id === task.column); const next = columns[Math.max(0, Math.min(columns.length - 1, index + direction))]; if (next.id !== task.column) { task.column = next.id; render(); status.textContent = `Moved task to ${next.title}.`; } }
function attachEvents() { board.querySelectorAll(".card").forEach(card => { card.addEventListener("dragstart", () => { draggedId = Number(card.dataset.task); card.style.opacity = ".5"; }); card.addEventListener("dragend", () => { draggedId = null; card.style.opacity = ""; }); card.querySelectorAll("[data-move]").forEach(button => button.addEventListener("click", event => { event.stopPropagation(); move(Number(card.dataset.task), Number(button.dataset.move)); })); card.querySelector("[data-delete]").addEventListener("click", event => { event.stopPropagation(); tasks = tasks.filter(task => task.id !== Number(card.dataset.task)); render(); status.textContent = "Task deleted."; }); }); board.querySelectorAll(".column").forEach(column => { column.addEventListener("dragover", event => { event.preventDefault(); column.classList.add("drop-active"); }); column.addEventListener("dragleave", () => column.classList.remove("drop-active")); column.addEventListener("drop", event => { event.preventDefault(); column.classList.remove("drop-active"); const task = tasks.find(item => item.id === draggedId); if (task) { task.column = column.dataset.column; render(); status.textContent = `Task moved to ${column.querySelector("h3").textContent}.`; } }); }); }
document.querySelector("#task-form").addEventListener("submit", event => { event.preventDefault(); const input = document.querySelector("#task-input"); const text = input.value.trim(); if (!text) { status.textContent = "Write a task before adding it."; return; } tasks.push({ id: Date.now(), text, column: "backlog" }); input.value = ""; render(); status.textContent = "Task added to Backlog."; });
document.querySelector("#clear-button").addEventListener("click", () => { tasks = []; render(); status.textContent = "Board cleared."; });
document.querySelector("#reset-button").addEventListener("click", () => { tasks = sample.map(task => ({ ...task })); render(); status.textContent = "Sample board restored."; });
render();
