const canvas=document.querySelector("#pixel-canvas"),gridSizeInput=document.querySelector("#grid-size"),gridSummary=document.querySelector("#grid-summary"),colorInput=document.querySelector("#color-input"),colorValue=document.querySelector("#color-value"),palette=document.querySelector("#palette"),status=document.querySelector("#status"),clearButton=document.querySelector("#clear-button"),downloadButton=document.querySelector("#download-button");
const paletteColors=["#1f2937","#ffffff","#e85d75","#f59e0b","#f7d154","#54b37d","#287b78","#4d7cfe","#8b5cf6","#c084fc","#a16207","#78350f","#f3d5bd","#94a3b8","#64748b","#000000"];
let size=16, cells=[], tool="pencil", drawing=false, currentColor=colorInput.value;
function setStatus(message){status.textContent=message}
function makePalette(){palette.replaceChildren();for(const color of paletteColors){const button=document.createElement("button");button.className="swatch";button.type="button";button.style.backgroundColor=color;button.title=color;button.setAttribute("aria-label",`Use color ${color}`);button.addEventListener("click",()=>setColor(color));palette.append(button)}updatePalette()}
function updatePalette(){palette.querySelectorAll(".swatch").forEach(button=>button.classList.toggle("active",button.style.backgroundColor.toLowerCase()===currentColor.toLowerCase()))}
function setColor(color){currentColor=color.toUpperCase();colorInput.value=color;colorValue.textContent=currentColor;updatePalette();if(tool==="eyedropper")setTool("pencil");setStatus(`Selected color ${currentColor}.`)}
function setTool(next){tool=next;document.querySelectorAll(".tool").forEach(button=>{const active=button.dataset.tool===tool;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});setStatus(`${next[0].toUpperCase()+next.slice(1)} tool selected.`)}
function resetGrid(){cells=Array.from({length:size*size},()=>"");canvas.width=size*16;canvas.height=size*16;gridSummary.textContent=`${size} × ${size}`;draw();setStatus("Grid cleared.")}
function draw(){const cellSize=canvas.width/size;const context=canvas.getContext("2d");context.clearRect(0,0,canvas.width,canvas.height);context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const value=cells[y*size+x];if(value){context.fillStyle=value;context.fillRect(x*cellSize,y*cellSize,cellSize,cellSize)}}context.strokeStyle="rgba(39,35,31,.16)";context.lineWidth=1;for(let i=0;i<=size;i++){const p=Math.round(i*cellSize)+.5;context.beginPath();context.moveTo(p,0);context.lineTo(p,canvas.height);context.stroke();context.beginPath();context.moveTo(0,p);context.lineTo(canvas.width,p);context.stroke()}}
function getCell(event){const rect=canvas.getBoundingClientRect();return {x:Math.floor((event.clientX-rect.left)/rect.width*size),y:Math.floor((event.clientY-rect.top)/rect.height*size)}}
function fill(startX,startY,color){const target=cells[startY*size+startX];if(target===color)return;const queue=[[startX,startY]],seen=new Set();while(queue.length){const [x,y]=queue.pop(),key=`${x},${y}`;if(seen.has(key)||x<0||y<0||x>=size||y>=size||cells[y*size+x]!==target)continue;seen.add(key);cells[y*size+x]=color;queue.push([x+1,y],[x-1,y],[x,y+1],[x,y-1])}}
function useCell(x,y){if(x<0||y<0||x>=size||y>=size)return;const index=y*size+x;if(tool==="eyedropper"){if(cells[index])setColor(cells[index]);else setStatus("That cell has no color.");return}if(tool==="fill")fill(x,y,currentColor);else cells[index]=tool==="eraser"?"":currentColor;draw()}
canvas.addEventListener("pointerdown",event=>{event.preventDefault();drawing=true;canvas.setPointerCapture(event.pointerId);const {x,y}=getCell(event);useCell(x,y)});canvas.addEventListener("pointermove",event=>{if(!drawing||tool==="fill"||tool==="eyedropper")return;const {x,y}=getCell(event);useCell(x,y)});canvas.addEventListener("pointerup",()=>{drawing=false});canvas.addEventListener("pointercancel",()=>{drawing=false});
document.querySelectorAll(".tool").forEach(button=>button.addEventListener("click",()=>setTool(button.dataset.tool)));gridSizeInput.addEventListener("change",()=>{size=Number(gridSizeInput.value);resetGrid()});colorInput.addEventListener("input",()=>setColor(colorInput.value));clearButton.addEventListener("click",resetGrid);downloadButton.addEventListener("click",()=>{const exportCanvas=document.createElement("canvas"),scale=32;exportCanvas.width=size*scale;exportCanvas.height=size*scale;const context=exportCanvas.getContext("2d");context.imageSmoothingEnabled=false;context.fillStyle="#fff";context.fillRect(0,0,exportCanvas.width,exportCanvas.height);for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(cells[y*size+x]){context.fillStyle=cells[y*size+x];context.fillRect(x*scale,y*scale,scale,scale)}exportCanvas.toBlob(blob=>{const url=URL.createObjectURL(blob),link=document.createElement("a");link.download=`pixel-art-${size}x${size}.png`;link.href=url;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("PNG exported.")},"image/png")});makePalette();resetGrid();
