const typeInput=document.querySelector("#type-input"),angleInput=document.querySelector("#angle-input"),angleValue=document.querySelector("#angle-value"),angleRow=document.querySelector("#angle-row"),stopsElement=document.querySelector("#stops"),preview=document.querySelector("#gradient-preview"),cssOutput=document.querySelector("#css-output"),stopSummary=document.querySelector("#stop-summary"),status=document.querySelector("#status"),addStop=document.querySelector("#add-stop"),copyButton=document.querySelector("#copy-button"),copyInline=document.querySelector("#copy-inline"),downloadButton=document.querySelector("#download-button"),resetButton=document.querySelector("#reset-button");
let stops=[{color:"#f06a8d",position:0},{color:"#5b7cfa",position:100}];
function setStatus(message,error=false){status.className=error?"status error":"status";status.textContent=message}
function normalize(){stops.sort((a,b)=>a.position-b.position);stops.forEach(stop=>{stop.position=Math.max(0,Math.min(100,Math.round(Number(stop.position)||0)))});}
function css(){normalize();const values=stops.map(stop=>`${stop.color} ${stop.position}%`).join(", ");if(typeInput.value==="radial")return `radial-gradient(circle, ${values})`;if(typeInput.value==="conic")return `conic-gradient(from ${angleInput.value}deg, ${values})`;return `linear-gradient(${angleInput.value}deg, ${values})`}
function render(){normalize();const value=css();preview.style.background=value;cssOutput.textContent=`background: ${value};`;angleValue.textContent=`${angleInput.value}°`;angleRow.hidden=typeInput.value==="radial";stopSummary.textContent=`${stops.length} stops`;setStatus("Gradient updated.")}
function renderStops(){stopsElement.replaceChildren();stops.forEach((stop,index)=>{const row=document.createElement("div");row.className="stop-row";const color=document.createElement("input");color.type="color";color.value=stop.color;color.setAttribute("aria-label",`Color stop ${index+1} color`);const hex=document.createElement("input");hex.type="text";hex.value=stop.color;hex.maxLength=7;hex.setAttribute("aria-label",`Color stop ${index+1} hex value`);const position=document.createElement("input");position.type="number";position.min=0;position.max=100;position.value=stop.position;position.setAttribute("aria-label",`Color stop ${index+1} position`);const remove=document.createElement("button");remove.className="remove-stop";remove.type="button";remove.textContent="×";remove.setAttribute("aria-label",`Remove color stop ${index+1}`);color.addEventListener("input",()=>{stop.color=color.value;hex.value=stop.color;render()});hex.addEventListener("change",()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value)){stop.color=hex.value;color.value=stop.color;render()}else{hex.value=stop.color;setStatus("Use a six-digit hex color such as #7C3AED.",true)}});position.addEventListener("input",()=>{stop.position=position.value;render()});remove.disabled=stops.length<=2;remove.addEventListener("click",()=>{stops.splice(index,1);renderStops();render()});row.append(color,hex,position,remove);stopsElement.append(row)})}
async function copy(){try{await navigator.clipboard.writeText(`background: ${css()};`);setStatus("CSS gradient copied.")}catch{setStatus("Clipboard access was unavailable.",true)}}
typeInput.addEventListener("change",render);angleInput.addEventListener("input",render);addStop.addEventListener("click",()=>{stops.push({color:"#f5c542",position:50});renderStops();render()});copyButton.addEventListener("click",copy);copyInline.addEventListener("click",copy);downloadButton.addEventListener("click",()=>{const blob=new Blob([`background: ${css()};\n`],{type:"text/css"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.download="gradient.css";link.href=url;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("CSS gradient downloaded.")});resetButton.addEventListener("click",()=>{typeInput.value="linear";angleInput.value=135;stops=[{color:"#f06a8d",position:0},{color:"#5b7cfa",position:100}];renderStops();render();setStatus("Gradient reset.")});renderStops();render();
