const fileInput=document.querySelector("#file-input"),dropZone=document.querySelector("#drop-zone"),imagePreview=document.querySelector("#image-preview"),status=document.querySelector("#status"),countInput=document.querySelector("#count-input"),countValue=document.querySelector("#count-value"),copyButton=document.querySelector("#copy-button"),downloadButton=document.querySelector("#download-button"),resetButton=document.querySelector("#reset-button"),paletteElement=document.querySelector("#palette"),paletteSummary=document.querySelector("#palette-summary"),dimensions=document.querySelector("#dimensions");
const MAX_FILE_SIZE=20*1024*1024;let image=null,url=null,colors=[],name="palette";
function setStatus(message,error=false){status.className=error?"status error":"status";status.textContent=message}
function setEnabled(enabled){countInput.disabled=!enabled;copyButton.disabled=!enabled||!colors.length;downloadButton.disabled=!enabled||!colors.length;resetButton.disabled=!enabled}
function hex(r,g,b){return `#${[r,g,b].map(value=>value.toString(16).padStart(2,"0")).join("").toUpperCase()}`}
function extract(){if(!image)return;const canvas=document.createElement("canvas"),max=90,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext("2d");context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height).data,buckets=new Map();for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]<128)continue;const r=Math.round(pixels[i]/32)*32,g=Math.round(pixels[i+1]/32)*32,b=Math.round(pixels[i+2]/32)*32,key=`${Math.min(255,r)},${Math.min(255,g)},${Math.min(255,b)}`;buckets.set(key,(buckets.get(key)||0)+1)}const count=Number(countInput.value);colors=[...buckets.entries()].sort((a,b)=>b[1]-a[1]).slice(0,count).map(([value,frequency])=>{const [r,g,b]=value.split(",").map(Number);return {hex:hex(r,g,b),r,g,b,frequency}});renderPalette();setStatus("Palette updated.")}
function renderPalette(){paletteElement.replaceChildren();const total=colors.reduce((sum,color)=>sum+color.frequency,0)||1;for(const color of colors){const card=document.createElement("article");card.className="color-card";const swatch=document.createElement("div");swatch.className="color-swatch";swatch.style.backgroundColor=color.hex;const info=document.createElement("div");info.className="color-info";const title=document.createElement("strong");title.textContent=color.hex;const percentage=document.createElement("span");percentage.textContent=`${Math.round(color.frequency/total*100)}% of sampled pixels`;const button=document.createElement("button");button.type="button";button.textContent="Copy hex";button.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(color.hex);setStatus(`${color.hex} copied.`)}catch{setStatus("Clipboard access was unavailable.",true)}});info.append(title,percentage,button);card.append(swatch,info);paletteElement.append(card)}paletteSummary.textContent=`${colors.length} colors`;setEnabled(Boolean(image))}
function clear(){if(url)URL.revokeObjectURL(url);url=null;image=null;colors=[];fileInput.value="";imagePreview.innerHTML='<p class="empty-state">Your image will appear here.</p>';paletteElement.innerHTML='<p class="empty-state">Extracted colors will appear here.</p>';paletteSummary.textContent="No colors yet";dimensions.textContent="No image loaded";setEnabled(false);setStatus("Choose an image to begin.")}
function load(file){if(!file)return;clear();resetButton.disabled=false;if(!file.type.startsWith("image/"))return setStatus("Please choose an image file.",true);if(file.size>MAX_FILE_SIZE)return setStatus("That image is larger than the 20 MB limit.",true);name=file.name.replace(/\.[^.]+$/," ").trim()||"palette";url=URL.createObjectURL(file);const next=new Image();next.onload=()=>{if(!next.naturalWidth)return setStatus("That image has no usable dimensions.",true);image=next;const preview=document.createElement("img");preview.src=url;preview.alt="Original image used for palette extraction";imagePreview.replaceChildren(preview);dimensions.textContent=`${image.naturalWidth} × ${image.naturalHeight} px`;setEnabled(true);extract()};next.onerror=()=>setStatus("That image could not be read. Try another file.",true);next.src=url}
function paletteText(){return `:root {\n${colors.map((color,index)=>`  --color-${index+1}: ${color.hex};`).join("\n")}\n}`}
fileInput.addEventListener("change",()=>load(fileInput.files[0]));for(const event of ["dragenter","dragover"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add("is-dragging")});for(const event of ["dragleave","drop"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove("is-dragging")});dropZone.addEventListener("drop",e=>load(e.dataTransfer.files[0]));countInput.addEventListener("input",()=>{countValue.textContent=countInput.value;extract()});copyButton.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(paletteText());setStatus("CSS palette copied.")}catch{setStatus("Clipboard access was unavailable.",true)}});downloadButton.addEventListener("click",()=>{const blob=new Blob([paletteText()],{type:"text/plain"}),downloadUrl=URL.createObjectURL(blob),link=document.createElement("a");link.download=`${name}-palette.txt`;link.href=downloadUrl;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000);setStatus("Palette downloaded.")});resetButton.addEventListener("click",clear);setEnabled(false);
