const fileInput=document.querySelector("#file-input"),dropZone=document.querySelector("#drop-zone"),status=document.querySelector("#status"),resetButton=document.querySelector("#reset-button"),formatInput=document.querySelector("#format-input"),qualityRow=document.querySelector("#quality-row"),qualityInput=document.querySelector("#quality-input"),qualityValue=document.querySelector("#quality-value"),downloadButton=document.querySelector("#download-button"),originalPreview=document.querySelector("#original-preview"),convertedPreview=document.querySelector("#converted-preview"),originalFormat=document.querySelector("#original-format"),convertedSize=document.querySelector("#converted-size"),dimensions=document.querySelector("#dimensions");
const MAX_FILE_SIZE=20*1024*1024; let sourceImage=null,sourceUrl=null,sourceName="image",latestBlob=null,latestUrl=null;
function setStatus(message,error=false){status.className=error?"status error":"status";status.textContent=message;}
function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(2)} MB`;}
function setEnabled(enabled){formatInput.disabled=!enabled;qualityInput.disabled=!enabled||formatInput.value==="image/png";downloadButton.disabled=!enabled||!latestBlob;}
function updateQuality(){qualityValue.textContent=`${qualityInput.value}%`;qualityValue.value=qualityValue.textContent;}
function updateFormat(){const lossy=formatInput.value!=="image/png";qualityRow.hidden=!lossy;setEnabled(Boolean(sourceImage));convert();}
function convert(){if(!sourceImage)return;const canvas=document.createElement("canvas");canvas.width=sourceImage.naturalWidth;canvas.height=sourceImage.naturalHeight;const context=canvas.getContext("2d");if(!context)return setStatus("Your browser could not create a conversion surface.",true);if(formatInput.value==="image/jpeg"){context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);}context.drawImage(sourceImage,0,0);const quality=Number(qualityInput.value)/100;canvas.toBlob(blob=>{if(!blob)return setStatus("This browser could not create the selected format.",true);if(latestUrl)URL.revokeObjectURL(latestUrl);latestBlob=blob;latestUrl=URL.createObjectURL(blob);convertedPreview.innerHTML="";const image=document.createElement("img");image.src=latestUrl;image.alt=`Converted ${formatInput.options[formatInput.selectedIndex].text} preview`;convertedPreview.append(image);convertedSize.textContent=formatBytes(blob.size);setEnabled(true);setStatus("Conversion preview updated.");},formatInput.value,formatInput.value==="image/png"?undefined:quality);}
function clearImage(){if(sourceUrl)URL.revokeObjectURL(sourceUrl);if(latestUrl)URL.revokeObjectURL(latestUrl);sourceUrl=null;latestUrl=null;sourceImage=null;latestBlob=null;fileInput.value="";originalPreview.innerHTML='<p class="empty-state">Original preview</p>';convertedPreview.innerHTML='<p class="empty-state">Converted preview</p>';originalFormat.textContent="—";convertedSize.textContent="—";dimensions.textContent="No image loaded";resetButton.disabled=true;setEnabled(false);setStatus("No image selected yet.");}
function loadFile(file){if(!file)return;clearImage();resetButton.disabled=false;if(!file.type.startsWith("image/"))return setStatus("Please choose an image file.",true);if(file.size>MAX_FILE_SIZE)return setStatus("That image is larger than the 20 MB limit.",true);sourceName=file.name.replace(/\.[^.]+$/," ").trim()||"image";sourceUrl=URL.createObjectURL(file);const image=new Image();image.onload=()=>{if(!image.naturalWidth||!image.naturalHeight)return setStatus("That image has no usable dimensions.",true);sourceImage=image;const original=document.createElement("img");original.src=sourceUrl;original.alt="Original selected image preview";originalPreview.replaceChildren(original);originalFormat.textContent=file.type||"Image";dimensions.textContent=`${image.naturalWidth} × ${image.naturalHeight} px`;setEnabled(true);convert();setStatus(`Loaded ${image.naturalWidth} × ${image.naturalHeight} pixels.`);};image.onerror=()=>setStatus("That image could not be read. Try another file.",true);image.src=sourceUrl;}
function download(){if(!latestBlob)return;const extension=formatInput.value.split("/")[1].replace("jpeg","jpg"),url=URL.createObjectURL(latestBlob),link=document.createElement("a");link.download=`${sourceName}-converted.${extension}`;link.href=url;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(`Downloaded converted ${extension.toUpperCase()} image.`);}
fileInput.addEventListener("change",()=>loadFile(fileInput.files[0]));for(const event of ["dragenter","dragover"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add("is-dragging")});for(const event of ["dragleave","drop"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove("is-dragging")});dropZone.addEventListener("drop",event=>loadFile(event.dataTransfer.files[0]));formatInput.addEventListener("change",updateFormat);qualityInput.addEventListener("input",()=>{updateQuality();convert()});downloadButton.addEventListener("click",download);resetButton.addEventListener("click",clearImage);updateQuality();setEnabled(false);
