const boardElement = document.querySelector("#board"); const scoreElement = document.querySelector("#score"); const bestElement = document.querySelector("#best"); const status = document.querySelector("#status"); const bestKey = "2048-best-score"; let board; let score = 0; let previous = null; let touchStart = null;
function loadBest() { try { return Number(localStorage.getItem(bestKey)) || 0; } catch { return 0; } } let best = loadBest();
function emptyCells() { const cells = []; board.forEach((row, y) => row.forEach((value, x) => { if (!value) cells.push({ x, y }); })); return cells; }
function addTile() { const cells = emptyCells(); if (!cells.length) return; const cell = cells[Math.floor(Math.random() * cells.length)]; board[cell.y][cell.x] = Math.random() < .9 ? 2 : 4; }
function render() { boardElement.innerHTML = board.flat().map(value => `<div class="tile${value ? "" : " empty"}" role="gridcell" aria-label="${value || "Empty"} tile"${value ? ` data-value="${value}"` : ""}>${value || ""}</div>`).join(""); scoreElement.textContent = score; bestElement.textContent = best; }
function newGame() { board = Array.from({ length: 4 }, () => [0, 0, 0, 0]); score = 0; previous = null; addTile(); addTile(); render(); status.textContent = "Use arrow keys or swipe to begin."; status.className = "status"; }
function slide(line) { const compact = line.filter(Boolean); const result = []; for (let i = 0; i < compact.length; i++) { if (compact[i] === compact[i + 1]) { const merged = compact[i] * 2; result.push(merged); score += merged; i++; } else result.push(compact[i]); } while (result.length < 4) result.push(0); return result; }
function move(direction) { const before = JSON.stringify(board); const snapshot = { board: board.map(row => [...row]), score }; if (direction === "left" || direction === "right") board = board.map(row => { const line = direction === "left" ? row : [...row].reverse(); const slid = slide(line); return direction === "left" ? slid : slid.reverse(); }); else { const columns = [0, 1, 2, 3].map(x => board.map(row => row[x])); const moved = columns.map(column => { const line = direction === "up" ? column : [...column].reverse(); const slid = slide(line); return direction === "up" ? slid : slid.reverse(); }); board = Array.from({ length: 4 }, (_, y) => Array.from({ length: 4 }, (_, x) => moved[x][y])); } if (JSON.stringify(board) === before) { score = snapshot.score; return false; } previous = snapshot; addTile(); if (score > best) { best = score; try { localStorage.setItem(bestKey, String(best)); } catch {} } render(); if (board.flat().includes(2048)) { status.textContent = "You made 2048 — keep going or start a new game."; status.className = "status good"; } else if (!canMove()) endGame(); else { status.textContent = "Nice move. Keep merging."; status.className = "status"; } return true; }
function canMove() { if (emptyCells().length) return true; for (let y = 0; y < 4; y++) for (let x = 0; x < 4; x++) if ((board[y][x] === board[y + 1]?.[x]) || (board[y][x] === board[y]?.[x + 1])) return true; return false; }
function endGame() { status.textContent = `No moves left — final score ${score}.`; status.className = "status error"; }
function undo() { if (!previous) { status.textContent = "There is no move to undo yet."; return; } board = previous.board; score = previous.score; previous = null; render(); status.textContent = "Last move undone."; status.className = "status"; }
function handleDirection(direction) { move(direction); }
const keyDirections = { ArrowLeft: "left", a: "left", ArrowRight: "right", d: "right", ArrowUp: "up", w: "up", ArrowDown: "down", s: "down" }; document.addEventListener("keydown", event => { if (keyDirections[event.key]) { event.preventDefault(); handleDirection(keyDirections[event.key]); } }); document.querySelectorAll("[data-direction]").forEach(button => button.addEventListener("click", () => handleDirection(button.dataset.direction))); document.querySelector("#new-game").addEventListener("click", newGame); document.querySelector("#undo").addEventListener("click", undo); boardElement.addEventListener("touchstart", event => { touchStart = event.changedTouches[0]; }, { passive: true }); boardElement.addEventListener("touchend", event => { if (!touchStart) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.clientX; const dy = touch.clientY - touchStart.clientY; touchStart = null; if (Math.max(Math.abs(dx), Math.abs(dy)) < 24) return; handleDirection(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? "right" : "left") : (dy > 0 ? "down" : "up")); }, { passive: true }); newGame();
