const fileInput=document.querySelector("#file-input"),dropZone=document.querySelector("#drop-zone"),sourcePreview=document.querySelector("#source-preview"),output=document.querySelector("#ascii-output"),status=document.querySelector("#status"),widthInput=document.querySelector("#width-input"),widthValue=document.querySelector("#width-value"),charsetInput=document.querySelector("#charset-input"),customCharset=document.querySelector("#custom-charset"),invertInput=document.querySelector("#invert-input"),contrastInput=document.querySelector("#contrast-input"),contrastValue=document.querySelector("#contrast-value"),summary=document.querySelector("#summary"),copyButton=document.querySelector("#copy-button"),downloadButton=document.querySelector("#download-button"),resetButton=document.querySelector("#reset-button");
const MAX_FILE_SIZE=20*1024*1024;let image=null,url=null,art="",name="ascii-art";
function setStatus(message,error=false){status.className=error?"status error":"status";status.textContent=message}
function setEnabled(enabled){copyButton.disabled=!enabled;downloadButton.disabled=!enabled;resetButton.disabled=!enabled}
function chars(){return [...(customCharset.value||" .:-=+*#%@")].join("")}
function render(){if(!image)return;const width=Number(widthInput.value),charsValue=chars(),aspect=image.naturalHeight/image.naturalWidth,rows=Math.max(1,Math.round(width*aspect*.5)),canvas=document.createElement("canvas");canvas.width=width;canvas.height=rows;const context=canvas.getContext("2d");context.drawImage(image,0,0,width,rows);const pixels=context.getImageData(0,0,width,rows).data;const contrast=Number(contrastInput.value)/100;let lines=[];for(let y=0;y<rows;y++){let line="";for(let x=0;x<width;x++){const i=(y*width+x)*4;let brightness=(pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114)/255;brightness=(brightness-.5)*contrast+.5;brightness=Math.max(0,Math.min(1,brightness));if(invertInput.checked)brightness=1-brightness;line+=charsValue[Math.min(charsValue.length-1,Math.floor(brightness*(charsValue.length-1)))]}lines.push(line)}art=lines.join("\n");output.textContent=art;summary.textContent=`${width} × ${rows} characters`;widthValue.textContent=width;contrastValue.textContent=`${contrastInput.value}%`;setStatus("ASCII art updated.")}
function clear(){if(url)URL.revokeObjectURL(url);url=null;image=null;art="";fileInput.value="";sourcePreview.innerHTML='<p class="empty-state">Original preview</p>';output.innerHTML='<span class="empty-state">Your ASCII art will appear here.</span>';summary.textContent="No image loaded";setEnabled(false);setStatus("Choose an image to begin.")}
function load(file){if(!file)return;clear();resetButton.disabled=false;if(!file.type.startsWith("image/"))return setStatus("Please choose an image file.",true);if(file.size>MAX_FILE_SIZE)return setStatus("That image is larger than the 20 MB limit.",true);name=file.name.replace(/\.[^.]+$/," ").trim()||"ascii-art";url=URL.createObjectURL(file);const next=new Image();next.onload=()=>{if(!next.naturalWidth)return setStatus("That image has no usable dimensions.",true);image=next;const preview=document.createElement("img");preview.src=url;preview.alt="Original image used for ASCII conversion";sourcePreview.replaceChildren(preview);setEnabled(true);render()};next.onerror=()=>setStatus("That image could not be read. Try another file.",true);next.src=url}
fileInput.addEventListener("change",()=>load(fileInput.files[0]));for(const event of ["dragenter","dragover"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add("is-dragging")});for(const event of ["dragleave","drop"])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove("is-dragging")});dropZone.addEventListener("drop",e=>load(e.dataTransfer.files[0]));widthInput.addEventListener("input",render);contrastInput.addEventListener("input",render);invertInput.addEventListener("change",render);charsetInput.addEventListener("change",()=>{customCharset.value=charsetInput.value;render()});customCharset.addEventListener("input",render);copyButton.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(art);setStatus("ASCII art copied to the clipboard.")}catch{setStatus("Clipboard access was unavailable. Select the output and copy it manually.",true)}});downloadButton.addEventListener("click",()=>{const blob=new Blob([art],{type:"text/plain"}),downloadUrl=URL.createObjectURL(blob),link=document.createElement("a");link.download=`${name}.txt`;link.href=downloadUrl;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000);setStatus("ASCII art downloaded.")});resetButton.addEventListener("click",clear);setEnabled(false);
