const canvas = document.querySelector("#canvas");
const context = canvas.getContext("2d");
const seedInput = document.querySelector("#seed");
const complexity = document.querySelector("#complexity");
const symmetry = document.querySelector("#symmetry");
const palette = document.querySelector("#palette");
const status = document.querySelector("#status");
const palettes = { aurora: ["#b9f36e", "#69d7c4", "#637cff", "#ff9abd"], ember: ["#ffdb75", "#ff995f", "#e95b6e", "#7e3f8f"], ultraviolet: ["#f0a6ff", "#9f8cff", "#5b72ff", "#2de2e6"], meadow: ["#e8f58b", "#90dc83", "#49b58c", "#246b78"] };
function hashSeed(value) { let hash = 2166136261; for (const character of value) { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
function random(seed) { seed.value = (Math.imul(seed.value, 1664525) + 1013904223) >>> 0; return seed.value / 4294967296; }
function draw() {
  const seedText = seedInput.value.trim() || "untitled"; const state = { value: hashSeed(seedText) }; const forms = Number(complexity.value); const rays = Number(symmetry.value); const colors = palettes[palette.value]; const width = canvas.width; const height = canvas.height; const cx = width / 2; const cy = height / 2; const radius = Math.min(cx, cy) * .92;
  const background = context.createRadialGradient(cx, cy, 0, cx, cy, radius * 1.4); background.addColorStop(0, "#18251d"); background.addColorStop(1, "#080c0b"); context.fillStyle = background; context.fillRect(0, 0, width, height);
  context.save(); context.translate(cx, cy); context.globalCompositeOperation = "screen";
  for (let i = 0; i < forms; i++) { const angle = random(state) * (Math.PI * 2 / rays); const distance = 25 + random(state) * radius * .82; const length = 12 + random(state) * (radius * .38); const thickness = .7 + random(state) * 3.2; const hue = colors[Math.floor(random(state) * colors.length)]; context.save(); context.rotate(angle); context.strokeStyle = hue; context.globalAlpha = .25 + random(state) * .6; context.lineWidth = thickness; context.beginPath(); context.moveTo(distance, 0); context.quadraticCurveTo(distance + length * .45, (random(state) - .5) * 100, distance + length, (random(state) - .5) * 150); context.stroke(); context.restore(); }
  context.globalAlpha = .55; context.strokeStyle = colors[0]; context.lineWidth = 1; for (let i = 0; i < rays; i++) { context.rotate(Math.PI * 2 / rays); context.beginPath(); context.moveTo(0, 0); context.lineTo(radius * .9, 0); context.stroke(); } context.restore();
  context.save(); context.translate(cx, cy); context.globalCompositeOperation = "lighter"; for (let i = 0; i < Math.ceil(forms / 5); i++) { const angle = random(state) * Math.PI * 2; const distance = random(state) * radius * .8; const dot = 1 + random(state) * 5; context.fillStyle = colors[i % colors.length]; context.globalAlpha = .3 + random(state) * .5; context.beginPath(); context.arc(Math.cos(angle) * distance, Math.sin(angle) * distance, dot, 0, Math.PI * 2); context.fill(); } context.restore();
  document.querySelector("#seed-label").textContent = seedText; document.querySelector("#detail-label").textContent = `${forms} forms · ${rays}-fold symmetry`; status.textContent = `Generated locally from “${seedText}”.`; status.className = "status";
}
function updateLabels() { document.querySelector("#complexity-value").textContent = complexity.value; document.querySelector("#symmetry-value").textContent = `${symmetry.value} ${symmetry.value === "1" ? "ray" : "rays"}`; }
document.querySelector("#generate").addEventListener("click", draw); document.querySelector("#random-seed").addEventListener("click", () => { seedInput.value = Math.random().toString(36).slice(2, 10); draw(); }); document.querySelector("#download").addEventListener("click", () => { const link = document.createElement("a"); link.download = `${seedInput.value.trim() || "generative-art"}.png`; link.href = canvas.toDataURL("image/png"); link.click(); status.textContent = "PNG saved from the local canvas."; }); document.querySelector("#reset").addEventListener("click", () => { seedInput.value = "luminous-garden"; complexity.value = 58; symmetry.value = 8; palette.value = "aurora"; updateLabels(); draw(); }); [complexity, symmetry].forEach(input => input.addEventListener("input", () => { updateLabels(); draw(); })); palette.addEventListener("change", draw); seedInput.addEventListener("input", draw); updateLabels(); draw();
