const input = document.querySelector("#choices-input"); const wheel = document.querySelector("#wheel"); const status = document.querySelector("#status"); const result = document.querySelector("#result-output"); let rotation = 0; let spinning = false;
const colors = ["#c7f36b", "#ff9a6e", "#9dd9ff", "#dca6ff", "#f5d46b", "#7ee0c0", "#f59cba", "#b9c4ff"];
const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
function choices() { return input.value.split("\n").map(item => item.trim()).filter(Boolean).slice(0, 24); }
function slicePath(cx, cy, radius, start, end) { const x1 = cx + radius * Math.cos(start); const y1 = cy + radius * Math.sin(start); const x2 = cx + radius * Math.cos(end); const y2 = cy + radius * Math.sin(end); const large = end - start > Math.PI ? 1 : 0; return `M ${cx} ${cy} L ${x1} ${y1} A ${radius} ${radius} 0 ${large} 1 ${x2} ${y2} Z`; }
function render() { const items = choices(); document.querySelector("#choice-count").textContent = `${items.length} ${items.length === 1 ? "choice" : "choices"}`; if (!items.length) { wheel.innerHTML = ""; return; } const step = Math.PI * 2 / items.length; const parts = items.map((item, index) => { const start = -Math.PI / 2 + index * step; const end = start + step; const mid = start + step / 2; const x = 50 + 31 * Math.cos(mid); const y = 50 + 31 * Math.sin(mid); return `<path d="${slicePath(50, 50, 50, start, end)}" fill="${colors[index % colors.length]}" stroke="#171817" stroke-width=".7"></path><text x="${x}" y="${y}" fill="#17200c" text-anchor="middle" dominant-baseline="middle" font-size="${items.length > 10 ? 3.2 : 4.5}" font-weight="800" transform="rotate(${mid * 180 / Math.PI + 90} ${x} ${y})">${escapeHtml(item.slice(0, 15))}</text>`; }).join(""); wheel.innerHTML = `<svg viewBox="0 0 100 100" aria-hidden="true">${parts}</svg>`; }
function randomIndex(max) { const values = new Uint32Array(1); crypto.getRandomValues(values); return values[0] % max; }
function spin() { const items = choices(); if (spinning) return; if (items.length < 2) { status.className = "status error"; status.textContent = "Add at least two choices before spinning."; return; } spinning = true; result.textContent = "…"; status.className = "status"; status.textContent = "The wheel is deciding…"; const index = randomIndex(items.length); const segment = 360 / items.length; const target = 360 - (index * segment + segment / 2); rotation += 1440 + target - (rotation % 360); wheel.style.transform = `rotate(${rotation}deg)`; setTimeout(() => { result.textContent = items[index]; status.textContent = "Decision made locally."; spinning = false; }, 2450); }
input.addEventListener("input", render); document.querySelector("#spin-button").addEventListener("click", spin); document.querySelector("#sample-button").addEventListener("click", () => { input.value = "Pizza\nTacos\nSushi\nSalad"; result.textContent = "—"; render(); status.textContent = "Ready to spin."; }); document.querySelector("#clear-button").addEventListener("click", () => { input.value = ""; result.textContent = "—"; render(); status.textContent = "Add choices to begin."; }); render();
