const fileInput=document.querySelector('#file-input'),dropZone=document.querySelector('#drop-zone'),shadowInput=document.querySelector('#shadow-input'),highlightInput=document.querySelector('#highlight-input'),contrastInput=document.querySelector('#contrast-input'),contrastValue=document.querySelector('#contrast-value'),invertInput=document.querySelector('#invert-input'),preview=document.querySelector('#preview'),summary=document.querySelector('#summary'),status=document.querySelector('#status'),downloadButton=document.querySelector('#download-button'),resetButton=document.querySelector('#reset-button');
const MAX_FILE_SIZE=20*1024*1024;let image=null,url=null,latestCanvas=null;
function setStatus(message,error=false){status.className=error?'status error':'status';status.textContent=message}
function setEnabled(enabled){shadowInput.disabled=!enabled;highlightInput.disabled=!enabled;contrastInput.disabled=!enabled;invertInput.disabled=!enabled;downloadButton.disabled=!enabled;resetButton.disabled=!enabled}
function color(hex){return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]}
function render(){if(!image)return;const max=720,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),source=document.createElement('canvas'),sourceContext=source.getContext('2d');source.width=width;source.height=height;sourceContext.drawImage(image,0,0,width,height);const pixels=sourceContext.getImageData(0,0,width,height),low=color(shadowInput.value),high=color(highlightInput.value),contrast=Number(contrastInput.value)/100;for(let i=0;i<pixels.data.length;i+=4){let tone=(pixels.data[i]*.299+pixels.data[i+1]*.587+pixels.data[i+2]*.114)/255;tone=(tone-.5)*contrast+.5;tone=Math.max(0,Math.min(1,tone));if(invertInput.checked)tone=1-tone;pixels.data[i]=low[0]+(high[0]-low[0])*tone;pixels.data[i+1]=low[1]+(high[1]-low[1])*tone;pixels.data[i+2]=low[2]+(high[2]-low[2])*tone}sourceContext.putImageData(pixels,0,0);latestCanvas=source;preview.replaceChildren(source);source.setAttribute('role','img');source.setAttribute('aria-label',`Duotone preview, ${width} by ${height} pixels`);summary.textContent=`${width} × ${height} px`;contrastValue.textContent=`${contrastInput.value}%`;setStatus('Duotone preview updated.')}
function clear(){if(url)URL.revokeObjectURL(url);url=null;image=null;latestCanvas=null;fileInput.value='';preview.innerHTML='<p class="empty-state">Your duotone image will appear here.</p>';summary.textContent='No image loaded';setEnabled(false);setStatus('Choose an image to begin.')}
function load(file){if(!file)return;clear();resetButton.disabled=false;if(!file.type.startsWith('image/'))return setStatus('Please choose an image file.',true);if(file.size>MAX_FILE_SIZE)return setStatus('That image is larger than the 20 MB limit.',true);url=URL.createObjectURL(file);const next=new Image();next.onload=()=>{if(!next.naturalWidth)return setStatus('That image has no usable dimensions.',true);image=next;setEnabled(true);render()};next.onerror=()=>setStatus('That image could not be read.',true);next.src=url}
fileInput.addEventListener('change',()=>load(fileInput.files[0]));for(const event of ['dragenter','dragover'])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add('is-dragging')});for(const event of ['dragleave','drop'])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove('is-dragging')});dropZone.addEventListener('drop',e=>load(e.dataTransfer.files[0]));[shadowInput,highlightInput,contrastInput,invertInput].forEach(input=>input.addEventListener('input',render));downloadButton.addEventListener('click',()=>{if(!latestCanvas)return;latestCanvas.toBlob(blob=>{const downloadUrl=URL.createObjectURL(blob),link=document.createElement('a');link.download='duotone.png';link.href=downloadUrl;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000);setStatus('Duotone PNG downloaded.')},'image/png')});resetButton.addEventListener('click',()=>{shadowInput.value='#171d38';highlightInput.value='#f7c873';contrastInput.value=100;invertInput.checked=false;clear();setStatus('Duotone reset.')});setEnabled(false);
