const input = document.querySelector("#csv-input");
const tableOutput = document.querySelector("#table-output");
const status = document.querySelector("#status");
const filterInput = document.querySelector("#filter-input");
const rowCount = document.querySelector("#row-count");
const statsOutput = document.querySelector("#stats-output");
let headers = []; let rows = []; let sortColumn = -1; let sortDirection = 1;
const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
function parseCsv(text) { const result = []; let row = []; let value = ""; let quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i]; if (char === '"' && quoted && text[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { row.push(value); value = ""; } else if (char === "\n" && !quoted) { row.push(value.replace(/\r$/, "")); result.push(row); row = []; value = ""; } else value += char; } if (quoted) throw new Error("An open quote was found. Check the CSV fields."); if (value || row.length) { row.push(value.replace(/\r$/, "")); result.push(row); } return result.filter(item => item.some(cell => cell.trim() !== "")); }
function load(text) { try { const parsed = parseCsv(text); if (parsed.length < 1 || parsed[0].length < 1) throw new Error("No CSV rows were found."); headers = parsed[0].map((header, index) => header.trim() || `Column ${index + 1}`); rows = parsed.slice(1).map(row => headers.map((_, index) => row[index] || "")); sortColumn = -1; render(); status.className = "status"; status.textContent = `Loaded ${rows.length} ${rows.length === 1 ? "row" : "rows"} and ${headers.length} columns.`; } catch (error) { headers = []; rows = []; tableOutput.innerHTML = `<div class="empty-state">${escapeHtml(error.message)}</div>`; statsOutput.innerHTML = ""; rowCount.textContent = "0 rows"; status.className = "status error"; status.textContent = error.message; } }
function render() { const query = filterInput.value.trim().toLowerCase(); let visible = rows.map((row, index) => ({ row, index })).filter(item => item.row.some(cell => cell.toLowerCase().includes(query))); if (sortColumn >= 0) visible.sort((a, b) => a.row[sortColumn].localeCompare(b.row[sortColumn], undefined, { numeric: true, sensitivity: "base" }) * sortDirection); rowCount.textContent = `${visible.length} of ${rows.length} ${rows.length === 1 ? "row" : "rows"}`; tableOutput.innerHTML = `<table class="data-table"><thead><tr>${headers.map((header, index) => `<th scope="col"><button type="button" data-sort="${index}" aria-label="Sort by ${escapeHtml(header)}">${escapeHtml(header)} ${sortColumn === index ? (sortDirection === 1 ? "↑" : "↓") : "↕"}</button></th>`).join("")}</tr></thead><tbody>${visible.map(item => `<tr>${item.row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") || `<tr><td colspan="${headers.length}">No rows match this filter.</td></tr>`}</tbody></table>`; tableOutput.querySelectorAll("[data-sort]").forEach(button => button.addEventListener("click", () => { const column = Number(button.dataset.sort); if (sortColumn === column) sortDirection *= -1; else { sortColumn = column; sortDirection = 1; } render(); })); renderStats(); }
function renderStats() { statsOutput.innerHTML = headers.map((header, index) => { const numbers = rows.map(row => Number(row[index])).filter(value => Number.isFinite(value)); if (!numbers.length) return ""; const average = numbers.reduce((sum, value) => sum + value, 0) / numbers.length; return `<div class="stat-card"><span>${escapeHtml(header)} · numeric</span><strong>avg ${average.toLocaleString(undefined, { maximumFractionDigits: 2 })}</strong><span>min ${Math.min(...numbers)} · max ${Math.max(...numbers)}</span></div>`; }).join(""); }
filterInput.addEventListener("input", render);
document.querySelector("#load-button").addEventListener("click", () => load(input.value));
document.querySelector("#sample-button").addEventListener("click", () => { input.value = "name,team,score\nAda,Blue,98\nLin,Gold,87\nMika,Blue,93\nJo,Gold,91"; load(input.value); });
document.querySelector("#clear-button").addEventListener("click", () => { input.value = ""; filterInput.value = ""; headers = []; rows = []; tableOutput.innerHTML = "<div class=\"empty-state\">Your CSV table will appear here.</div>"; statsOutput.innerHTML = ""; rowCount.textContent = "0 rows"; status.className = "status"; status.textContent = "Drop or paste CSV to begin."; });
document.querySelector("#file-input").addEventListener("change", event => { const file = event.target.files[0]; if (file) file.text().then(text => { input.value = text; load(text); }); });
const dropZone = document.querySelector("#drop-zone");
["dragenter", "dragover"].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.style.borderColor = "var(--accent)"; }));
["dragleave", "drop"].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.style.borderColor = ""; }));
dropZone.addEventListener("drop", event => { const file = event.dataTransfer.files[0]; if (file) file.text().then(text => { input.value = text; load(text); }); });
input.value = "name,team,score\nAda,Blue,98\nLin,Gold,87\nMika,Blue,93\nJo,Gold,91";
load(input.value);
