const peopleList = document.querySelector("#people-list"); const itemsList = document.querySelector("#items-list"); const results = document.querySelector("#results"); const status = document.querySelector("#status"); const sharedCost = document.querySelector("#shared-cost"); const taxRate = document.querySelector("#tax-rate");
const samplePeople = [{ name: "Alex", weight: 1 }, { name: "Bea", weight: 1 }, { name: "Chen", weight: 1 }]; const sampleItems = [{ name: "Pasta", amount: 18, person: 0 }, { name: "Salad", amount: 12, person: 1 }];
function money(value) { return `$${value.toFixed(2)}`; } function number(value) { const parsed = Number.parseFloat(value); return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; }
function personRows() { return [...peopleList.querySelectorAll(".person-row")].map(row => ({ name: row.querySelector(".person-name").value.trim() || "Unnamed", weight: number(row.querySelector(".person-weight").value) })); }
function refreshPersonOptions() { const rows = [...itemsList.querySelectorAll(".item-row")]; rows.forEach(row => { const select = row.querySelector(".item-person"); const previous = select.value; select.innerHTML = personRows().map((person, index) => `<option value="${index}">${escapeHtml(person.name)}</option>`).join(""); select.value = [...select.options].some(option => option.value === previous) ? previous : "0"; }); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char])); }
function addPerson(person = { name: "", weight: 1 }) { const row = document.createElement("div"); row.className = "row person-row"; row.innerHTML = `<input class="person-name" aria-label="Person name" placeholder="Name" value="${escapeHtml(person.name)}"><input class="person-weight" aria-label="Share weight" type="number" min="0" step="0.5" value="${person.weight}"><button class="remove-button" type="button" aria-label="Remove person">×</button>`; peopleList.append(row); }
function addItem(item = { name: "", amount: 0, person: 0 }) { const row = document.createElement("div"); row.className = "row item-row"; row.innerHTML = `<input class="item-name" aria-label="Item name" placeholder="Item" value="${escapeHtml(item.name)}"><input class="item-amount" aria-label="Item amount" type="number" min="0" step="0.01" value="${item.amount}"><select class="item-person" aria-label="Who ordered this item"></select><button class="remove-button" type="button" aria-label="Remove item">×</button>`; itemsList.append(row); refreshPersonOptions(); row.querySelector(".item-person").value = String(item.person); }
function calculate() { const people = personRows(); const items = [...itemsList.querySelectorAll(".item-row")].map(row => ({ name: row.querySelector(".item-name").value.trim() || "Unnamed item", amount: number(row.querySelector(".item-amount").value), person: Number(row.querySelector(".item-person").value) || 0 })); const itemTotal = items.reduce((sum, item) => sum + item.amount, 0); const shared = number(sharedCost.value); const tax = (itemTotal + shared) * Math.min(100, number(taxRate.value)) / 100; const weightTotal = people.reduce((sum, person) => sum + person.weight, 0); const totals = people.map((person, index) => { const ownItems = items.filter(item => item.person === index).reduce((sum, item) => sum + item.amount, 0); const sharedPart = weightTotal ? (shared + tax) * person.weight / weightTotal : 0; return { ...person, ownItems, sharedPart, total: ownItems + sharedPart }; }); return { people, items, totals, grandTotal: itemTotal + shared + tax, weightTotal }; }
function render() { const data = calculate(); document.querySelector("#items-empty").hidden = data.items.length > 0; document.querySelector("#total-summary").textContent = `${money(data.grandTotal)} total`; results.innerHTML = data.people.length ? data.totals.map(person => `<article class="result${person.total ? " paid" : ""}"><div><span class="result-name">${escapeHtml(person.name)}</span><span class="result-detail">${money(person.ownItems)} items · ${money(person.sharedPart)} shared</span></div><strong class="result-amount">${money(person.total)}</strong></article>`).join("") : `<p class="empty-row">Add at least one person to see the split.</p>`; status.textContent = data.people.length && data.weightTotal ? "Split updates as you edit." : "Add people with a share weight greater than zero."; status.className = data.people.length && data.weightTotal ? "status" : "status error"; }
function reset() { peopleList.innerHTML = ""; itemsList.innerHTML = ""; samplePeople.forEach(addPerson); sampleItems.forEach(addItem); sharedCost.value = "10"; taxRate.value = "8.5"; render(); status.textContent = "Sample bill loaded."; status.className = "status"; }
document.querySelector("#add-person").addEventListener("click", () => { addPerson(); refreshPersonOptions(); render(); }); document.querySelector("#add-item").addEventListener("click", () => { addItem(); render(); }); document.querySelector("#reset-button").addEventListener("click", reset); [peopleList, itemsList, sharedCost, taxRate].forEach(element => element.addEventListener("input", () => { refreshPersonOptions(); render(); })); itemsList.addEventListener("change", render); document.querySelector("#people-list").addEventListener("click", event => { if (event.target.closest(".remove-button")) { event.target.closest(".person-row").remove(); refreshPersonOptions(); render(); } }); document.querySelector("#items-list").addEventListener("click", event => { if (event.target.closest(".remove-button")) { event.target.closest(".item-row").remove(); render(); } }); document.querySelector("#copy-button").addEventListener("click", async () => { const data = calculate(); const text = data.totals.map(person => `${person.name}: ${money(person.total)}`).join("\n"); try { await navigator.clipboard.writeText(`Expense split — ${money(data.grandTotal)} total\n${text}`); status.textContent = "Summary copied to the clipboard."; status.className = "status"; } catch { status.textContent = "Clipboard access is unavailable; select the results to copy them."; status.className = "status error"; } }); reset();
