const canvas = document.querySelector("#game"); const ctx = canvas.getContext("2d"); const status = document.querySelector("#status"); const scoreOutput = document.querySelector("#score"); const livesOutput = document.querySelector("#lives"); let ship; let asteroids; let bullets; let score; let lives; let running = false; let paused = false; let animation; let keys = {}; let lastTime = 0;
function wrap(entity) { if (entity.x < -20) entity.x = canvas.width + 20; if (entity.x > canvas.width + 20) entity.x = -20; if (entity.y < -20) entity.y = canvas.height + 20; if (entity.y > canvas.height + 20) entity.y = -20; }
function makeAsteroid(x = Math.random() * canvas.width, y = Math.random() * canvas.height, size = 3) { return { x, y, size, radius: size * 12, dx: (Math.random() - .5) * (size === 3 ? 1.4 : 2.2), dy: (Math.random() - .5) * (size === 3 ? 1.4 : 2.2), angle: Math.random() * Math.PI * 2, spin: (Math.random() - .5) * .03 }; }
function resetShip() { ship = { x: canvas.width / 2, y: canvas.height / 2, angle: -Math.PI / 2, dx: 0, dy: 0, cooldown: 0, invincible: 1.5 }; }
function setup() { asteroids = Array.from({ length: 7 }, () => makeAsteroid()); bullets = []; score = 0; lives = 3; resetShip(); updateHud(); draw(); }
function updateHud() { scoreOutput.textContent = score; livesOutput.textContent = lives; }
function fire() { if (ship.cooldown > 0 || bullets.length > 8) return; bullets.push({ x: ship.x + Math.cos(ship.angle) * 15, y: ship.y + Math.sin(ship.angle) * 15, dx: ship.dx + Math.cos(ship.angle) * 6, dy: ship.dy + Math.sin(ship.angle) * 6, life: 1.1 }); ship.cooldown = .18; }
function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
function splitAsteroid(target) { if (target.size > 1) { asteroids.push(makeAsteroid(target.x, target.y, target.size - 1), makeAsteroid(target.x, target.y, target.size - 1)); } }
function update(dt) { if (keys.ArrowLeft || keys.a) ship.angle -= 3.6 * dt; if (keys.ArrowRight || keys.d) ship.angle += 3.6 * dt; if (keys.ArrowUp || keys.w) { ship.dx += Math.cos(ship.angle) * 3.2 * dt; ship.dy += Math.sin(ship.angle) * 3.2 * dt; } if (keys[" "]) fire(); ship.x += ship.dx; ship.y += ship.dy; ship.dx *= .992; ship.dy *= .992; wrap(ship); ship.cooldown = Math.max(0, ship.cooldown - dt); ship.invincible = Math.max(0, ship.invincible - dt); bullets.forEach(bullet => { bullet.x += bullet.dx; bullet.y += bullet.dy; bullet.life -= dt; wrap(bullet); }); bullets = bullets.filter(bullet => bullet.life > 0); asteroids.forEach(asteroid => { asteroid.x += asteroid.dx; asteroid.y += asteroid.dy; asteroid.angle += asteroid.spin; wrap(asteroid); }); for (let i = bullets.length - 1; i >= 0; i--) { const bullet = bullets[i]; const hit = asteroids.find(asteroid => distance(bullet, asteroid) < asteroid.radius); if (hit) { bullets.splice(i, 1); asteroids.splice(asteroids.indexOf(hit), 1); splitAsteroid(hit); score += hit.size * 20; updateHud(); } } if (!ship.invincible && asteroids.some(asteroid => distance(ship, asteroid) < asteroid.radius + 10)) { lives--; updateHud(); if (!lives) return endGame(); resetShip(); } if (!asteroids.length) { asteroids = Array.from({ length: 5 + Math.min(8, score / 80), }, () => makeAsteroid()); status.textContent = "Wave clear — a new field is drifting in."; status.className = "status good"; } }
function draw() { ctx.fillStyle = "#07110b"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "#102719"; for (let x = 0; x < canvas.width; x += 26) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } asteroids.forEach(asteroid => { ctx.save(); ctx.translate(asteroid.x, asteroid.y); ctx.rotate(asteroid.angle); ctx.strokeStyle = asteroid.size === 3 ? "#ffad73" : "#9edb7d"; ctx.lineWidth = 2; ctx.beginPath(); for (let i = 0; i < 8; i++) { const angle = i * Math.PI / 4; const radius = asteroid.radius * (.78 + (i % 3) * .1); ctx.lineTo(Math.cos(angle) * radius, Math.sin(angle) * radius); } ctx.closePath(); ctx.stroke(); ctx.restore(); }); bullets.forEach(bullet => { ctx.fillStyle = "#fff2ae"; ctx.fillRect(bullet.x - 2, bullet.y - 2, 4, 4); }); if (ship.invincible <= 0 || Math.floor(ship.invincible * 10) % 2) { ctx.save(); ctx.translate(ship.x, ship.y); ctx.rotate(ship.angle); ctx.strokeStyle = "#c7f487"; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(16, 0); ctx.lineTo(-12, -10); ctx.lineTo(-7, 0); ctx.lineTo(-12, 10); ctx.closePath(); ctx.stroke(); ctx.restore(); } }
function frame(time) { if (!running || paused) return; const dt = Math.min(.04, (time - lastTime) / 1000 || .016); lastTime = time; update(dt); draw(); animation = requestAnimationFrame(frame); }
function start() { if (running && !paused) return; if (!running) setup(); running = true; paused = false; status.textContent = "Clear the field and keep moving."; status.className = "status good"; animation = requestAnimationFrame(frame); }
function endGame() { running = false; paused = false; cancelAnimationFrame(animation); status.textContent = `Game over — score ${score}.`; status.className = "status error"; draw(); }
document.addEventListener("keydown", event => { if (["ArrowLeft", "ArrowRight", "ArrowUp", "a", "d", "w", " "].includes(event.key)) { event.preventDefault(); keys[event.key] = true; if (event.key === " ") start(); } }); document.addEventListener("keyup", event => { keys[event.key] = false; }); document.querySelector("#start-button").addEventListener("click", start); document.querySelector("#pause-button").addEventListener("click", () => { if (!running) return; paused = !paused; status.textContent = paused ? "Paused." : "Clear the field and keep moving."; status.className = "status"; if (!paused) animation = requestAnimationFrame(frame); }); document.querySelectorAll("[data-control]").forEach(button => { const control = button.dataset.control; button.addEventListener("pointerdown", () => { if (control === "fire") fire(); else if (control === "left") keys.a = true; else if (control === "right") keys.d = true; else keys.ArrowUp = true; }); button.addEventListener("pointerup", () => { keys.a = false; keys.d = false; keys.ArrowUp = false; }); }); setup();
