const sourceTabs=document.querySelectorAll('.source-tab'),emojiControls=document.querySelector('#emoji-controls'),imageControls=document.querySelector('#image-controls'),emojiInput=document.querySelector('#emoji-input'),emojiBg=document.querySelector('#emoji-bg'),fileInput=document.querySelector('#file-input'),dropZone=document.querySelector('#drop-zone'),radiusInput=document.querySelector('#radius-input'),radiusValue=document.querySelector('#radius-value'),previews=document.querySelector('#previews'),htmlOutput=document.querySelector('#html-output'),status=document.querySelector('#status'),downloadAll=document.querySelector('#download-all'),resetButton=document.querySelector('#reset-button');
const sizes=[16,32,48,180];let source='emoji',image=null,url=null;
function setStatus(message,error=false){status.className=error?'status error':'status';status.textContent=message}
function getCanvas(size){const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const context=canvas.getContext('2d');context.clearRect(0,0,size,size);const radius=size*Number(radiusInput.value)/100;context.beginPath();context.roundRect(0,0,size,size,radius);context.clip();if(source==='image'&&image)context.drawImage(image,0,0,size,size);else{context.fillStyle=emojiBg.value;context.fillRect(0,0,size,size);context.font=`${size*.72}px sans-serif`;context.textAlign='center';context.textBaseline='middle';context.fillText(emojiInput.value||'✨',size/2,size*.54)}return canvas}
function render(){previews.replaceChildren();for(const size of sizes){const card=document.createElement('div');card.className='favicon-card';const canvas=getCanvas(size);canvas.setAttribute('aria-label',`${size} by ${size} favicon preview`);const label=document.createElement('span');label.textContent=`${size} × ${size}`;card.append(canvas,label);previews.append(card)}radiusValue.textContent=`${radiusInput.value}%`;htmlOutput.textContent='<link rel="icon" type="image/png" sizes="32x32" href="favicon-32.png">';setStatus('Favicon previews updated.')}
function setSource(next){source=next;sourceTabs.forEach(tab=>{const active=tab.dataset.source===source;tab.classList.toggle('active',active);tab.setAttribute('aria-pressed',String(active))});emojiControls.hidden=source!=='emoji';imageControls.hidden=source!=='image';render()}
function loadFile(file){if(!file)return;if(!file.type.startsWith('image/'))return setStatus('Please choose an image file.',true);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);const next=new Image();next.onload=()=>{image=next;setSource('image');setStatus('Image source loaded.')};next.onerror=()=>setStatus('That image could not be read.',true);next.src=url}
function download(){sizes.forEach(size=>{getCanvas(size).toBlob(blob=>{const downloadUrl=URL.createObjectURL(blob),link=document.createElement('a');link.download=`favicon-${size}.png`;link.href=downloadUrl;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000)},'image/png')});setStatus('Favicon PNGs downloaded.')}
sourceTabs.forEach(tab=>tab.addEventListener('click',()=>setSource(tab.dataset.source)));[emojiInput,emojiBg,radiusInput].forEach(input=>input.addEventListener('input',render));fileInput.addEventListener('change',()=>loadFile(fileInput.files[0]));for(const event of ['dragenter','dragover'])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add('is-dragging')});for(const event of ['dragleave','drop'])dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove('is-dragging')});dropZone.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));downloadAll.addEventListener('click',download);resetButton.addEventListener('click',()=>{if(url)URL.revokeObjectURL(url);url=null;image=null;source='emoji';emojiInput.value='🌈';emojiBg.value='#18212b';radiusInput.value=20;setSource('emoji');setStatus('Favicon reset.')});render();
