const storageKey = "clipboard-scratchpad-snippets";
const form = document.querySelector("#snippet-form"); const input = document.querySelector("#snippet-input"); const search = document.querySelector("#search-input"); const list = document.querySelector("#snippet-list"); const status = document.querySelector("#status"); let snippets = load();
function load() { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "[]"); return Array.isArray(saved) ? saved.filter(item => item && typeof item.text === "string") : []; } catch { return []; } }
function save() { try { localStorage.setItem(storageKey, JSON.stringify(snippets)); } catch { status.textContent = "Storage is unavailable; this session will not persist."; status.className = "status error"; } }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char])); }
function render() { const query = search.value.trim().toLowerCase(); const visible = snippets.filter(item => item.text.toLowerCase().includes(query)); document.querySelector("#count").textContent = `${snippets.length} ${snippets.length === 1 ? "snippet" : "snippets"}`; list.innerHTML = visible.length ? visible.map(item => `<article class="snippet${item.pinned ? " pinned" : ""}"><div class="snippet-top"><p class="snippet-text">${escapeHtml(item.text)}</p><div class="snippet-actions"><button class="icon-button${item.pinned ? " pin" : ""}" type="button" data-action="pin" data-id="${item.id}" aria-label="${item.pinned ? "Unpin" : "Pin"} snippet">${item.pinned ? "Pinned" : "Pin"}</button><button class="icon-button" type="button" data-action="copy" data-id="${item.id}">Copy</button><button class="icon-button" type="button" data-action="delete" data-id="${item.id}">Delete</button></div></div><p class="snippet-meta">${item.pinned ? "Pinned · " : ""}${new Date(item.createdAt).toLocaleString()}</p></article>`).join("") : `<p class="empty">${query ? "No snippets match that search." : "Nothing saved yet. Add a snippet above."}</p>`; }
form.addEventListener("submit", event => { event.preventDefault(); const text = input.value.trim(); if (!text) { status.textContent = "Add some text before saving."; status.className = "status error"; return; } snippets.unshift({ id: crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`, text, pinned: false, createdAt: Date.now() }); save(); input.value = ""; document.querySelector("#char-count").textContent = "0 / 5000"; status.textContent = "Snippet saved locally."; status.className = "status"; render(); });
input.addEventListener("input", () => { document.querySelector("#char-count").textContent = `${input.value.length} / 5000`; }); search.addEventListener("input", render);
list.addEventListener("click", async event => { const button = event.target.closest("button"); if (!button) return; const item = snippets.find(snippet => snippet.id === button.dataset.id); if (!item) return; if (button.dataset.action === "pin") { item.pinned = !item.pinned; snippets.sort((a, b) => Number(b.pinned) - Number(a.pinned)); save(); render(); status.textContent = item.pinned ? "Snippet pinned." : "Snippet unpinned."; } if (button.dataset.action === "delete") { snippets = snippets.filter(snippet => snippet.id !== item.id); save(); render(); status.textContent = "Snippet deleted."; } if (button.dataset.action === "copy") { try { await navigator.clipboard.writeText(item.text); status.textContent = "Copied to the clipboard."; } catch { status.textContent = "Clipboard access is unavailable; select the text to copy it."; status.className = "status error"; } } });
document.querySelector("#clear-button").addEventListener("click", () => { if (!snippets.length) { status.textContent = "There are no snippets to clear."; return; } snippets = []; save(); render(); status.textContent = "All snippets cleared."; }); render();
