const input = document.querySelector("#cron-input");
const status = document.querySelector("#status");
const descriptionOutput = document.querySelector("#description-output");
const occurrenceList = document.querySelector("#occurrence-list");
const countOutput = document.querySelector("#count-output");
const monthNames = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
const dayNames = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
function parseField(text, min, max, names = []) { const values = new Set(); text.toUpperCase().split(",").forEach(part => { const [base, stepText] = part.split("/"); const step = stepText ? Number(stepText) : 1; if (!Number.isInteger(step) || step < 1) throw new Error(`Invalid step in “${part}”.`); let start = min; let end = max; if (base !== "*") { const range = base.split("-"); const convert = value => names.indexOf(value) >= 0 ? (names.indexOf(value) + (min === 1 ? 1 : 0)) : Number(value); start = convert(range[0]); end = range[1] ? convert(range[1]) : start; } if (!Number.isInteger(start) || !Number.isInteger(end) || start < min || end > max || start > end) throw new Error(`Value out of range in “${part}”.`); for (let value = start; value <= end; value += step) values.add(value); }); return values; }
function parseCron(expression) { const fields = expression.trim().split(/\s+/); if (fields.length !== 5) throw new Error("Use exactly five fields: minute hour day-of-month month day-of-week."); return { minute: parseField(fields[0], 0, 59), hour: parseField(fields[1], 0, 23), dom: parseField(fields[2], 1, 31), month: parseField(fields[3], 1, 12, monthNames), dow: parseField(fields[4], 0, 6, dayNames), raw: fields }; }
function matches(date, cron) { if (!cron.month.has(date.getMonth() + 1) || !cron.minute.has(date.getMinutes()) || !cron.hour.has(date.getHours())) return false; const dom = cron.dom.has(date.getDate()); const dow = cron.dow.has(date.getDay()); const domWildcard = cron.raw[2] === "*"; const dowWildcard = cron.raw[4] === "*"; return domWildcard && dowWildcard ? true : domWildcard ? dow : dowWildcard ? dom : dom || dow; }
function describe(cron) { const [minute, hour, dom, month, dow] = cron.raw; if (minute.startsWith("*/")) return `Every ${minute.slice(2)} minutes${hour !== "*" ? ` during hour field “${hour}”` : ""}.`; if (minute === "0" && hour !== "*" && dom === "*" && month === "*" && dow === "*") return `Every day at ${String(hour).padStart(2, "0")}:00.`; if (dom === "*" && month === "*" && dow === "1-5" && minute === "0") return `Every weekday at ${String(hour).padStart(2, "0")}:00.`; return `At minute ${minute}, hour ${hour}, on day ${dom} of month ${month}, and weekday ${dow}.`; }
function visualize() { try { const cron = parseCron(input.value); descriptionOutput.textContent = describe(cron); const results = []; const cursor = new Date(); cursor.setSeconds(0, 0); cursor.setMinutes(cursor.getMinutes() + 1); for (let i = 0; i < 105120 && results.length < 8; i++) { if (matches(cursor, cron)) results.push(new Date(cursor)); cursor.setMinutes(cursor.getMinutes() + 1); } if (!results.length) throw new Error("No occurrences found in the next two years."); occurrenceList.innerHTML = results.map(date => `<li><time>${date.toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" })}</time><span>${date.toISOString()}</span></li>`).join(""); countOutput.textContent = `${results.length} results`; status.className = "status"; status.textContent = "Valid expression. Times shown in your local time zone."; } catch (error) { descriptionOutput.textContent = "—"; occurrenceList.innerHTML = `<li class="empty">${error.message}</li>`; countOutput.textContent = "0 results"; status.className = "status error"; status.textContent = error.message; } }
document.querySelector("#visualize-button").addEventListener("click", visualize);
document.querySelector("#now-button").addEventListener("click", visualize);
document.querySelector("#clear-button").addEventListener("click", () => { input.value = ""; descriptionOutput.textContent = "—"; occurrenceList.innerHTML = "<li class=\"empty\">Visualize an expression to see upcoming times.</li>"; countOutput.textContent = "0 results"; status.className = "status"; status.textContent = "Ready to visualize."; });
document.querySelectorAll("[data-cron]").forEach(button => button.addEventListener("click", () => { input.value = button.dataset.cron; visualize(); }));
document.querySelector("#timezone-label").textContent = `Your zone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}`;
visualize();
