const canvas = document.querySelector("#canvas");
const context = canvas.getContext("2d");
const seedInput = document.querySelector("#seed");
const coast = document.querySelector("#coast");
const detail = document.querySelector("#detail");
const palette = document.querySelector("#palette");
const status = document.querySelector("#status");
const colorSets = { lagoon: ["#123c4a", "#1b6270", "#d8bd76", "#86a95b", "#477c4f", "#295c4a", "#173c37"], autumn: ["#173f48", "#2b6970", "#e0bc78", "#c98e50", "#9a603c", "#5a4d38", "#2f3f35"], night: ["#111b39", "#273c68", "#c9ae77", "#78936b", "#446b61", "#2b4d55", "#18283a"] };
function hash(value) { let result = 2166136261; for (const character of value) { result ^= character.charCodeAt(0); result = Math.imul(result, 16777619); } return result >>> 0; }
function noiseFactory(seed) { const values = Array.from({ length: 256 }, (_, index) => { const x = Math.sin(seed + index * 12.9898) * 43758.5453; return x - Math.floor(x); }); return (x, y, scale) => { const px = x / scale; const py = y / scale; const x0 = Math.floor(px); const y0 = Math.floor(py); const tx = px - x0; const ty = py - y0; const smooth = value => value * value * (3 - 2 * value); const sample = (ix, iy) => values[(Math.abs(ix * 37 + iy * 71) + seed) % 256]; const top = sample(x0, y0) * (1 - smooth(tx)) + sample(x0 + 1, y0) * smooth(tx); const bottom = sample(x0, y0 + 1) * (1 - smooth(tx)) + sample(x0 + 1, y0 + 1) * smooth(tx); return top * (1 - smooth(ty)) + bottom * smooth(ty); }; }
function draw() {
  const colors = colorSets[palette.value]; const seedText = seedInput.value.trim() || "untitled"; const seed = hash(seedText); const field = noiseFactory(seed % 256); const octaves = Number(detail.value); const threshold = Number(coast.value) / 100; const cell = 7; const cols = Math.ceil(canvas.width / cell); const rows = Math.ceil(canvas.height / cell); context.fillStyle = colors[0]; context.fillRect(0, 0, canvas.width, canvas.height);
  for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) { const dx = (x + .5) / cols - .5; const dy = (y + .5) / rows - .5; const radial = Math.max(0, 1 - Math.sqrt(dx * dx * 1.6 + dy * dy) * 1.72); let value = 0; let weight = 1; let total = 0; for (let octave = 0; octave < octaves; octave++) { value += field(x, y, 18 / (2 ** octave)) * weight; total += weight; weight *= .52; } value = value / total * .72 + radial * .72; if (value > threshold) { const level = Math.min(colors.length - 1, Math.floor((value - threshold) / (1 - threshold) * (colors.length - 2)) + 2); context.fillStyle = colors[level]; context.fillRect(x * cell, y * cell, cell + 1, cell + 1); } }
  document.querySelector("#map-label").textContent = seedText; document.querySelector("#coast-value").textContent = `${coast.value}%`; document.querySelector("#detail-value").textContent = `${detail.value} ${detail.value === "1" ? "octave" : "octaves"}`; status.textContent = `Generated “${seedText}” locally.`; status.className = "status";
}
document.querySelector("#generate").addEventListener("click", draw); document.querySelector("#random").addEventListener("click", () => { seedInput.value = Math.random().toString(36).slice(2, 10); draw(); }); [coast, detail].forEach(input => input.addEventListener("input", draw)); palette.addEventListener("change", draw); seedInput.addEventListener("input", draw); document.querySelector("#download").addEventListener("click", () => { const link = document.createElement("a"); link.download = `${seedInput.value.trim() || "island"}.png`; link.href = canvas.toDataURL("image/png"); link.click(); status.textContent = "PNG saved from the local canvas."; }); draw();
