const boardElement = document.querySelector("#board"); const status = document.querySelector("#status"); const difficulty = document.querySelector("#difficulty"); const settings = { beginner: [9, 9, 10], intermediate: [12, 12, 25] }; let rows; let columns; let mineTotal; let cells; let started; let finished; let timer; let seconds; let longPress;
function keyFor() { return `minesweeper-best-${difficulty.value}`; } function bestTimes() { try { return JSON.parse(localStorage.getItem("minesweeper-bests") || "{}"); } catch { return {}; } } function formatTime(value) { return `${value}s`; }
function config() { if (difficulty.value !== "custom") return settings[difficulty.value]; const r = Math.min(20, Math.max(5, Number.parseInt(document.querySelector("#rows").value, 10) || 10)); const c = Math.min(20, Math.max(5, Number.parseInt(document.querySelector("#columns").value, 10) || 10)); const max = Math.max(1, r * c - 9); const m = Math.min(max, Math.max(1, Number.parseInt(document.querySelector("#mines").value, 10) || 1)); document.querySelector("#rows").value = r; document.querySelector("#columns").value = c; document.querySelector("#mines").value = m; return [r, c, m]; }
function neighbors(index) { const y = Math.floor(index / columns); const x = index % columns; const list = []; for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) { const nx = x + dx; const ny = y + dy; if ((dx || dy) && nx >= 0 && nx < columns && ny >= 0 && ny < rows) list.push(ny * columns + nx); } return list; }
function plantMines(first) { const blocked = new Set([first, ...neighbors(first)]); const choices = [...Array(rows * columns).keys()].filter(index => !blocked.has(index)); for (let i = choices.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [choices[i], choices[j]] = [choices[j], choices[i]]; } choices.slice(0, mineTotal).forEach(index => { cells[index].mine = true; }); cells.forEach((cell, index) => { cell.number = neighbors(index).filter(neighbor => cells[neighbor].mine).length; }); }
function render() { boardElement.style.gridTemplateColumns = `repeat(${columns}, 1fr)`; boardElement.innerHTML = cells.map((cell, index) => `<button class="cell${cell.revealed ? " revealed" : ""}${cell.flagged ? " flagged" : ""}${cell.mine && finished ? " mine" : ""}" data-index="${index}" role="gridcell" aria-label="${cell.revealed ? (cell.mine ? "Mine" : `${cell.number || "Empty"} adjacent mines`) : cell.flagged ? "Flagged hidden cell" : "Hidden cell"}">${cell.flagged ? "⚑" : cell.revealed ? (cell.mine ? "✹" : cell.number || "") : ""}</button>`).join(""); document.querySelector("#mine-count").textContent = Math.max(0, mineTotal - cells.filter(cell => cell.flagged).length); document.querySelector("#time").textContent = formatTime(seconds); const best = bestTimes(); ["beginner", "intermediate", "custom"].forEach(key => document.querySelector(`#best-${key}`).textContent = best[key] ? formatTime(best[key]) : "—"); }
function reveal(index) { if (finished || cells[index].flagged || cells[index].revealed) return; if (!started) { plantMines(index); started = true; timer = setInterval(() => { seconds++; render(); }, 1000); } const cell = cells[index]; cell.revealed = true; if (cell.mine) return lose(); if (!cell.number) neighbors(index).forEach(reveal); if (cells.filter(item => !item.mine && !item.revealed).length === 0) win(); render(); }
function toggleFlag(index) { if (finished || cells[index].revealed) return; cells[index].flagged = !cells[index].flagged; render(); }
function lose() { finished = true; clearInterval(timer); cells.forEach(cell => { if (cell.mine) cell.revealed = true; }); status.textContent = "A mine found you. Try a fresh field."; status.className = "status error"; render(); }
function win() { finished = true; clearInterval(timer); const best = bestTimes(); if (!best[keyFor()] || seconds < best[keyFor()]) { best[keyFor()] = seconds; try { localStorage.setItem("minesweeper-bests", JSON.stringify(best)); } catch {} status.textContent = `Field cleared in ${seconds} seconds — new best!`; } else status.textContent = `Field cleared in ${seconds} seconds.`; status.className = "status good"; render(); }
function newGame() { clearInterval(timer); [rows, columns, mineTotal] = config(); cells = Array.from({ length: rows * columns }, () => ({ mine: false, number: 0, revealed: false, flagged: false })); started = false; finished = false; seconds = 0; document.querySelector("#mine-count").textContent = mineTotal; status.textContent = "Reveal a square to begin. Your first reveal is safe."; status.className = "status"; render(); }
boardElement.addEventListener("click", event => { const cell = event.target.closest(".cell"); if (cell) reveal(Number(cell.dataset.index)); }); boardElement.addEventListener("contextmenu", event => { event.preventDefault(); const cell = event.target.closest(".cell"); if (cell) toggleFlag(Number(cell.dataset.index)); }); boardElement.addEventListener("touchstart", event => { const cell = event.target.closest(".cell"); if (!cell) return; longPress = setTimeout(() => { toggleFlag(Number(cell.dataset.index)); longPress = null; }, 550); }, { passive: true }); boardElement.addEventListener("touchend", () => { if (longPress) { clearTimeout(longPress); longPress = null; } }); difficulty.addEventListener("change", () => { document.querySelector("#custom-settings").hidden = difficulty.value !== "custom"; newGame(); }); document.querySelector("#new-game").addEventListener("click", newGame); ["rows", "columns", "mines"].forEach(id => document.querySelector(`#${id}`).addEventListener("change", newGame)); newGame();
