const canvas = document.querySelector("#game"); const ctx = canvas.getContext("2d"); const grid = 20; const cell = canvas.width / grid; const scoreOutput = document.querySelector("#score"); const bestOutput = document.querySelector("#best"); const status = document.querySelector("#status"); const scoresList = document.querySelector("#scores-list"); const scoreKey = "snake-high-scores"; let snake; let food; let direction; let queued; let score; let timer; let running = false; let paused = false;
function loadScores() { try { const value = JSON.parse(localStorage.getItem(scoreKey) || "[]"); return Array.isArray(value) ? value.filter(score => Number.isFinite(score)).slice(0, 5) : []; } catch { return []; } } let scores = loadScores();
function renderScores() { bestOutput.textContent = scores[0] || 0; scoresList.innerHTML = scores.length ? scores.map(value => `<li><span>Run</span><strong>${value}</strong></li>`).join("") : "<li class=\"empty\">Your best runs will appear here.</li>"; }
function resetBoard() { snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }]; direction = { x: 1, y: 0 }; queued = direction; score = 0; scoreOutput.textContent = score; placeFood(); draw(); }
function placeFood() { const open = []; for (let y = 0; y < grid; y++) for (let x = 0; x < grid; x++) if (!snake.some(part => part.x === x && part.y === y)) open.push({ x, y }); food = open[Math.floor(Math.random() * open.length)]; }
function draw() { ctx.fillStyle = "#0d160e"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "#162519"; ctx.lineWidth = 1; for (let i = 1; i < grid; i++) { ctx.beginPath(); ctx.moveTo(i * cell, 0); ctx.lineTo(i * cell, canvas.height); ctx.moveTo(0, i * cell); ctx.lineTo(canvas.width, i * cell); ctx.stroke(); } ctx.fillStyle = "#ffad72"; ctx.beginPath(); ctx.arc(food.x * cell + cell / 2, food.y * cell + cell / 2, cell * .29, 0, Math.PI * 2); ctx.fill(); snake.forEach((part, index) => { ctx.fillStyle = index ? "#79b84e" : "#c4f47b"; ctx.fillRect(part.x * cell + 2, part.y * cell + 2, cell - 4, cell - 4); }); }
function tick() { if (!running || paused) return; direction = queued; const head = { x: snake[0].x + direction.x, y: snake[0].y + direction.y }; const hitWall = head.x < 0 || head.x >= grid || head.y < 0 || head.y >= grid; const hitSelf = snake.some(part => part.x === head.x && part.y === head.y); if (hitWall || hitSelf) return endGame(); snake.unshift(head); if (head.x === food.x && head.y === food.y) { score += 10; scoreOutput.textContent = score; placeFood(); speedUp(); } else snake.pop(); draw(); }
function speedUp() { clearInterval(timer); timer = setInterval(tick, Math.max(70, 155 - score * 2)); }
function start() { if (running && !paused) return; if (!running) { resetBoard(); running = true; } paused = false; speedUp(); status.textContent = "Collect fruit and avoid the walls."; status.className = "status good"; document.querySelector("#start-button").textContent = "Restart game"; }
function endGame() { running = false; paused = false; clearInterval(timer); scores = [score, ...scores].sort((a, b) => b - a).slice(0, 5); try { localStorage.setItem(scoreKey, JSON.stringify(scores)); } catch {} renderScores(); status.textContent = `Game over — you scored ${score}.`; status.className = "status error"; }
function turn(next) { if (next.x === -direction.x && next.y === -direction.y) return; queued = next; if (!running) start(); }
document.addEventListener("keydown", event => { const keys = { ArrowUp: { x: 0, y: -1 }, w: { x: 0, y: -1 }, ArrowDown: { x: 0, y: 1 }, s: { x: 0, y: 1 }, ArrowLeft: { x: -1, y: 0 }, a: { x: -1, y: 0 }, ArrowRight: { x: 1, y: 0 }, d: { x: 1, y: 0 } }; if (keys[event.key]) { event.preventDefault(); turn(keys[event.key]); } }); document.querySelectorAll("[data-direction]").forEach(button => button.addEventListener("click", () => { const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } }; turn(directions[button.dataset.direction]); })); document.querySelector("#start-button").addEventListener("click", () => { running = false; clearInterval(timer); start(); }); document.querySelector("#pause-button").addEventListener("click", () => { if (!running) return; paused = !paused; status.textContent = paused ? "Game paused." : "Collect fruit and avoid the walls."; status.className = "status"; }); document.querySelector("#clear-scores").addEventListener("click", () => { scores = []; try { localStorage.removeItem(scoreKey); } catch {} renderScores(); status.textContent = "High scores cleared."; status.className = "status"; }); resetBoard(); renderScores();
