const canvas = document.querySelector('#world');
const ctx = canvas.getContext('2d');
const controls = { plants: document.querySelector('#plants'), herbivores: document.querySelector('#herbivores'), predators: document.querySelector('#predators'), speed: document.querySelector('#speed') };
const counts = { plants: document.querySelector('#plant-count'), herbivores: document.querySelector('#herbivore-count'), predators: document.querySelector('#predator-count') };
const outputs = { plants: document.querySelector('#plants-value'), herbivores: document.querySelector('#herbivores-value'), predators: document.querySelector('#predators-value'), speed: document.querySelector('#speed-value') };
const colors = { plants: '#9be2b5', herbivores: '#f0ca79', predators: '#ec8d88' };
let world = { plants: [], herbivores: [], predators: [] }, generation = 0, running = false, timer;
const randomPoint = () => ({ x: 28 + Math.random() * (canvas.width - 56), y: 28 + Math.random() * (canvas.height - 56), phase: Math.random() * Math.PI * 2 });
function makePopulation(type, count) { return Array.from({ length: count }, randomPoint).map(point => ({ ...point, type, energy: type === 'plants' ? 1 : 2 })); }
function reset() { generation = 0; world = { plants: makePopulation('plants', +controls.plants.value), herbivores: makePopulation('herbivores', +controls.herbivores.value), predators: makePopulation('predators', +controls.predators.value) }; document.querySelector('#empty').hidden = true; document.querySelector('#message').textContent = 'Press Start simulation to begin.'; render(); }
function nearest(from, list) { let target, distance = Infinity; for (const item of list) { const d = Math.hypot(item.x - from.x, item.y - from.y); if (d < distance) { distance = d; target = item; } } return { target, distance }; }
function step() {
  const next = { plants: [...world.plants], herbivores: [], predators: [] };
  const eaten = new Set();
  world.herbivores.forEach((animal) => { const meal = nearest(animal, world.plants); const fed = meal.target && meal.distance < 95; if (fed) { eaten.add(meal.target); animal.energy = Math.min(4, animal.energy + 1); } else animal.energy -= .45; const survivor = animal.energy > 0; if (survivor) { next.herbivores.push({ ...animal, x: Math.max(18, Math.min(canvas.width - 18, animal.x + (Math.random() - .5) * 55)), y: Math.max(18, Math.min(canvas.height - 18, animal.y + (Math.random() - .5) * 55)), phase: animal.phase + .1 }); if (animal.energy > 2.8 && Math.random() < .13) next.herbivores.push({ ...animal, energy: 1.5, x: animal.x + 8, y: animal.y + 8 }); } });
  next.plants = next.plants.filter(plant => !eaten.has(plant));
  if (next.plants.length < 110 && Math.random() < .72) next.plants.push({ ...randomPoint(), type: 'plants', energy: 1 });
  world.predators.forEach((animal) => { const meal = nearest(animal, next.herbivores); const fed = meal.target && meal.distance < 115; if (fed) { const index = next.herbivores.indexOf(meal.target); if (index >= 0) next.herbivores.splice(index, 1); animal.energy = Math.min(5, animal.energy + 1.2); } else animal.energy -= .5; if (animal.energy > 0) { next.predators.push({ ...animal, x: Math.max(18, Math.min(canvas.width - 18, animal.x + (Math.random() - .5) * 45)), y: Math.max(18, Math.min(canvas.height - 18, animal.y + (Math.random() - .5) * 45)), phase: animal.phase + .08 }); if (animal.energy > 3.5 && Math.random() < .1) next.predators.push({ ...animal, energy: 2, x: animal.x + 8, y: animal.y + 8 }); } });
  world = next; generation += 1; render();
  if (!world.plants.length && !world.herbivores.length && !world.predators.length) { running = false; clearInterval(timer); document.querySelector('#message').textContent = 'The habitat is empty. Reset to try a new balance.'; }
}
function drawGroup(items, color, size) { ctx.fillStyle = color; items.forEach(item => { const pulse = Math.sin(item.phase + generation * .04) * 1.5; ctx.beginPath(); ctx.arc(item.x, item.y, size + pulse, 0, Math.PI * 2); ctx.fill(); }); }
function render() { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#122119'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(155,226,181,.08)'; for (let x = 30; x < canvas.width; x += 45) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } for (let y = 30; y < canvas.height; y += 45) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke(); } drawGroup(world.plants, colors.plants, 4); drawGroup(world.herbivores, colors.herbivores, 7); drawGroup(world.predators, colors.predators, 10); Object.keys(counts).forEach(key => counts[key].textContent = world[key].length); document.querySelector('#generation').textContent = `Generation ${generation}`; document.querySelector('#run-state').textContent = running ? 'Running' : 'Paused'; document.querySelector('#toggle').textContent = running ? 'Pause simulation' : 'Start simulation'; document.querySelector('#empty').hidden = world.plants.length + world.herbivores.length + world.predators.length > 0; }
function updateOutputs() { Object.keys(controls).forEach(key => { outputs[key].textContent = key === 'speed' ? `${controls[key].value}×` : controls[key].value; }); }
function toggle() { running = !running; clearInterval(timer); if (running) { document.querySelector('#message').textContent = 'The food web is evolving in real time.'; timer = setInterval(step, 1050 / +controls.speed.value); } else document.querySelector('#message').textContent = 'Simulation paused. Step once or resume when ready.'; render(); }
document.querySelector('#toggle').addEventListener('click', toggle); document.querySelector('#step').addEventListener('click', () => { if (running) toggle(); document.querySelector('#message').textContent = 'Advanced one generation.'; step(); }); document.querySelector('#reset').addEventListener('click', () => { running = false; clearInterval(timer); reset(); });
Object.values(controls).forEach(input => input.addEventListener('input', () => { updateOutputs(); if (!running && input !== controls.speed) reset(); if (running && input === controls.speed) toggle(); }));
updateOutputs(); reset();
