const input = document.querySelector("#text-input");
const sample = "A good draft gives each idea enough room to breathe. Read it once for meaning, then once for rhythm. Short sentences can create momentum, while longer sentences make space for nuance and context.";
const savedDraft = "reading-time-analyzer-draft";
const $ = selector => document.querySelector(selector);
function countSyllables(word) { const clean = word.toLowerCase().replace(/[^a-z]/g, ""); if (!clean) return 0; if (clean.length <= 3) return 1; const groups = clean.replace(/(?:e|es|ed)$/, "").match(/[aeiouy]+/g); return Math.max(1, groups ? groups.length : 1); }
function analyze(text) { const words = text.match(/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+(?:['’-][A-Za-zÀ-ÖØ-öø-ÿ0-9]+)*/g) || []; const sentences = text.split(/[.!?]+/).map(sentence => sentence.trim()).filter(Boolean); const paragraphs = text.split(/\n\s*\n/).map(paragraph => paragraph.trim()).filter(Boolean); const syllables = words.reduce((total, word) => total + countSyllables(word), 0); const wordCount = words.length; const sentenceCount = sentences.length; const score = wordCount && sentenceCount ? 206.835 - 1.015 * (wordCount / sentenceCount) - 84.6 * (syllables / wordCount) : 0; const grade = wordCount && sentenceCount ? .39 * (wordCount / sentenceCount) + 11.8 * (syllables / wordCount) - 15.59 : 0; return { wordCount, sentenceCount, paragraphCount: paragraphs.length, score: Math.max(0, Math.min(100, score)), grade: Math.max(0, grade), average: sentenceCount ? wordCount / sentenceCount : 0 }; }
function render() { const text = input.value; const result = analyze(text); $("#word-count").textContent = `${result.wordCount.toLocaleString()} ${result.wordCount === 1 ? "word" : "words"}`; $("#char-count").textContent = `${text.length.toLocaleString()} / 50,000 characters`; $("#plain-char-count").textContent = text.length.toLocaleString(); $("#sentence-count").textContent = result.sentenceCount; $("#paragraph-count").textContent = result.paragraphCount; $("#average-sentence").textContent = result.sentenceCount ? `${result.average.toFixed(1)} words` : "—"; $("#reading-time").textContent = result.wordCount ? `${Math.max(1, Math.ceil(result.wordCount / 200))} min` : "—"; $("#reading-score").textContent = result.wordCount ? Math.round(result.score) : "—"; $("#grade-score").textContent = result.wordCount ? `Grade ${result.grade.toFixed(1)}` : "—"; $("#reading-label").textContent = result.wordCount ? (result.score >= 60 ? "Comfortable reading" : result.score >= 30 ? "More complex text" : "Very complex text") : "Flesch score"; $("#status").textContent = result.wordCount ? "Analysis updates as you write." : "Start typing to see your reading profile."; $("#status").className = "status"; }
input.addEventListener("input", () => { try { localStorage.setItem(savedDraft, input.value); } catch {} render(); }); $("#sample-button").addEventListener("click", () => { input.value = sample; render(); try { localStorage.setItem(savedDraft, input.value); } catch {} $("#status").textContent = "Sample text loaded."; }); $("#clear-button").addEventListener("click", () => { input.value = ""; try { localStorage.removeItem(savedDraft); } catch {} render(); $("#status").textContent = "Text cleared."; });
try { input.value = localStorage.getItem(savedDraft) || ""; } catch {} render();
