let mode = "work"; let cycle = 1; let running = false; let endTime = 0; let remaining = 25 * 60; let interval;
const timeOutput = document.querySelector("#time-output"); const ring = document.querySelector("#ring"); const status = document.querySelector("#status"); const startButton = document.querySelector("#start-button");
function duration() { const value = Number(document.querySelector(mode === "work" ? "#work-minutes" : "#break-minutes").value); return Number.isFinite(value) && value > 0 ? Math.min(value, mode === "work" ? 120 : 60) * 60 : 0; }
function format(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function render() { const total = duration() || 1; timeOutput.textContent = format(Math.max(0, Math.ceil(remaining))); ring.style.setProperty("--progress", ((total - remaining) / total * 100).toFixed(2)); document.querySelector("#mode-label").textContent = mode === "work" ? "Focus time" : "Break time"; document.querySelector("#cycle-output").textContent = `Cycle ${cycle}`; document.querySelector("#state-output").textContent = running ? "In progress" : "Ready when you are"; startButton.textContent = running ? "Pause" : `Start ${mode === "work" ? "focus" : "break"}`; }
function switchMode(nextMode, auto = false) { mode = nextMode; remaining = duration(); running = auto; if (running) endTime = Date.now() + remaining * 1000; document.querySelectorAll("[data-mode]").forEach(button => { const active = button.dataset.mode === mode; button.classList.toggle("active", active); button.setAttribute("aria-pressed", active); }); status.textContent = mode === "work" ? "Ready to focus." : "A break is ready."; render(); }
function tick() { remaining = Math.max(0, Math.ceil((endTime - Date.now()) / 1000)); if (remaining <= 0) { clearInterval(interval); running = false; const next = mode === "work" ? "break" : "work"; if (mode === "work") cycle++; status.textContent = `${mode === "work" ? "Focus" : "Break"} complete. ${next === "work" ? "Back to focus." : "Take a break."}`; switchMode(next, document.querySelector("#auto-start").checked); } render(); }
function toggle() { if (!duration()) { status.className = "status error"; status.textContent = "Enter positive focus and break durations."; return; } if (running) { remaining = Math.max(0, Math.ceil((endTime - Date.now()) / 1000)); running = false; clearInterval(interval); status.textContent = "Paused. Resume when you are ready."; } else { endTime = Date.now() + remaining * 1000; running = true; interval = setInterval(tick, 250); status.textContent = `${mode === "work" ? "Focus" : "Break"} timer running.`; } render(); }
startButton.addEventListener("click", toggle); document.querySelector("#reset-button").addEventListener("click", () => { clearInterval(interval); running = false; cycle = 1; remaining = duration(); status.className = "status"; status.textContent = "Timer reset."; render(); }); document.querySelector("#skip-button").addEventListener("click", () => { clearInterval(interval); running = false; switchMode(mode === "work" ? "break" : "work"); }); document.querySelectorAll("[data-mode]").forEach(button => button.addEventListener("click", () => { clearInterval(interval); running = false; switchMode(button.dataset.mode); })); document.querySelectorAll("#work-minutes,#break-minutes").forEach(input => input.addEventListener("input", () => { if (!running) { remaining = duration(); render(); } })); remaining = duration(); render();
