const tracks = [
  { name: "Kick", type: "kick", pattern: [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0] },
  { name: "Snare", type: "snare", pattern: [0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0] },
  { name: "Hi-hat", type: "hat", pattern: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] },
  { name: "Bass", type: "bass", pattern: [1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0] }
];
const grid = document.querySelector("#track-grid"); const bpm = document.querySelector("#bpm"); const bpmValue = document.querySelector("#bpm-value"); const status = document.querySelector("#status"); let audio; let timer; let step = 0;
function buildGrid() { grid.innerHTML = tracks.map((track, trackIndex) => `<div class="track-row"><span class="track-name">${track.name}</span>${track.pattern.map((active, index) => `<button class="step ${active ? "active" : ""}" type="button" aria-label="${track.name}, step ${index + 1}" aria-pressed="${Boolean(active)}" data-track="${trackIndex}" data-step="${index}"></button>`).join("")}</div>`).join(""); grid.querySelectorAll(".step").forEach(button => button.addEventListener("click", () => { const track = tracks[Number(button.dataset.track)]; const index = Number(button.dataset.step); track.pattern[index] = track.pattern[index] ? 0 : 1; button.classList.toggle("active", Boolean(track.pattern[index])); button.setAttribute("aria-pressed", Boolean(track.pattern[index])); })); }
function tone(type, time) { if (!audio) return; const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.connect(gain); gain.connect(audio.destination); const duration = type === "hat" ? .045 : .14; if (type === "kick") { oscillator.frequency.setValueAtTime(130, time); oscillator.frequency.exponentialRampToValueAtTime(48, time + .12); gain.gain.setValueAtTime(.7, time); } else if (type === "snare") { oscillator.type = "triangle"; oscillator.frequency.setValueAtTime(180, time); gain.gain.setValueAtTime(.32, time); } else if (type === "bass") { oscillator.type = "square"; oscillator.frequency.setValueAtTime(65, time); gain.gain.setValueAtTime(.22, time); } else { oscillator.type = "square"; oscillator.frequency.setValueAtTime(5300, time); gain.gain.setValueAtTime(.1, time); } gain.gain.exponentialRampToValueAtTime(.001, time + duration); oscillator.start(time); oscillator.stop(time + duration); }
function tick() { tracks.forEach(track => { if (track.pattern[step]) tone(track.type, audio.currentTime); }); grid.querySelectorAll(".step").forEach(button => button.classList.toggle("playing", Number(button.dataset.step) === step)); step = (step + 1) % 16; }
async function play() { if (!audio) audio = new (window.AudioContext || window.webkitAudioContext)(); await audio.resume(); clearInterval(timer); step = 0; tick(); timer = setInterval(tick, (60 / Number(bpm.value) / 4) * 1000); status.textContent = "Playing locally — tap steps while the loop runs."; status.className = "status good"; }
function stop() { clearInterval(timer); timer = null; grid.querySelectorAll(".step").forEach(button => button.classList.remove("playing")); status.textContent = "Stopped. Your pattern is ready to play again."; status.className = "status"; }
document.querySelector("#play").addEventListener("click", play); document.querySelector("#stop").addEventListener("click", stop); bpm.addEventListener("input", () => { bpmValue.textContent = bpm.value; if (timer) play(); }); document.querySelector("#clear").addEventListener("click", () => { tracks.forEach(track => track.pattern.fill(0)); buildGrid(); status.textContent = "Pattern cleared."; }); document.querySelector("#random").addEventListener("click", () => { tracks.forEach((track, index) => track.pattern = track.pattern.map((_, stepIndex) => index === 2 ? Math.random() > .2 : Math.random() > (stepIndex % 4 === 0 ? .25 : .62))); buildGrid(); status.textContent = "A new pattern is ready."; }); bpmValue.textContent = bpm.value; buildGrid();
